---
title: "Dexamethasone treatment - Manuscript figures"
output:
  pdf_document: default
  html_document:
    df_print: paged
  toc: TRUE
---

```{r, echo = F}
knitr::opts_chunk$set(warning = F, message = F)
knitr::opts_chunk$set(fig.pos = "!H", out.extra = "")
#knitr::opts_chunk$set(tidy.opts=list(width.cutoff=80),tidy=TRUE)

```

```{r load_libraries, echo = F, message = F, warning = F}
library(readxl)
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(reshape2)
library(broom)
library(stringr)
#library(ggstatsplot)
```


```{r load_datasets}
# delta alpha clinical table
PNT <- read_excel("../2021-12-30_Dexa_Charite_UKK_PSV_all results a and d sanity check completed.xlsx") %>% 
  select(contains("Studie 1 von 2012-12-30_all results +basic clinical"),
         contains("PatID Studie 1"),
         contains("exclude"),
         contains("Tag PSO"),
         contains("PSO/PI"),
         contains("Zeitraum corrected"),
         contains("Serum"),
         contains("Dexa")) %>% 
  rename(Studie1 = `Studie 1 von 2012-12-30_all results +basic clinical`,
         PatID_Studie1 = `PatID Studie 1 von 2012-12-30_all results +basic clinical`, 
         exclude_immuno = `# exclude (immunosuppression, other)`,
         exclude_B.1.1.7 = `#exclude for B1.1.7`,
         exclude_B.1.617.2 = `#exclude for B.1.617.2`,
         TagPSO = `Tag PSO`,
         Timepoint = `Zeitraum corrected`,
         B.1.1.7 = `Serum ID50: Variant B.1.1.7`, 
         B.1.617.2 = `Serum ID50: Variant B.1.617.2`,
         Dexa = `Dexamethason von 2012-12-30_all results +basic clinical`) %>%
  mutate(PatID_Studie1 = str_replace(PatID_Studie1, c("C19-CB-"), "")) %>% 
  mutate(PatID_Studie1 = as.character(as.numeric(PatID_Studie1))) %>% 
  mutate(TagPSO = as.numeric(TagPSO)) %>%
  mutate(Studie1 = str_replace(Studie1, c("Pa-COVID-19"), "Pa-COVID")) %>% 
  mutate(PatID_Studie1 = paste(tolower(paste(substr(Studie1, 1, 2))), 
                               tolower(paste(substr(Studie1, (nchar(Studie1)-1), nchar(Studie1)), 
                                             PatID_Studie1, 
                                             sep = "")),
                               sep = "")) %>%
  mutate(exclude_immuno = as.numeric(replace_na(exclude_immuno, "0"))) %>% 
  filter(exclude_immuno == 0) %>% 
  mutate(exclude_B.1.1.7 = as.numeric(replace_na(exclude_B.1.1.7, "0"))) %>% 
  mutate(exclude_B.1.617.2 = as.numeric(replace_na(exclude_B.1.617.2, "0"))) %>% 
  mutate(Dexa = str_replace_all(Dexa, c("1" = "D+", "0" = "D-", "3" = "mild")))

# FACS results
facs <- read_excel("../20220104 Mastertable FACS incl. dead and VC.xlsx") %>% 
  select("Studie 1", 
         "PatID Studie 1", 
         "timepoints 2022", 
         "Tag PSO", 
         "Dexa", 
         "Marker 1", 
         "Marker 2", 
         "#CEFX-unstim log", 
         "#S1-unstim log", 
         "#S2-unstim log", 
         "#SEB-unstim log",
         "ausschliessen") %>%
  mutate(ausschliessen = replace_na(ausschliessen, 0)) %>% 
  rename(Studie1 = `Studie 1`, 
         PatID_Studie1 = `PatID Studie 1`, 
         Timepoint = `timepoints 2022`,
         TagPSO = `Tag PSO`, 
         Marker1 = `Marker 1`, 
         Marker2 = `Marker 2`) %>%
  rename(CEFX = `#CEFX-unstim log`, 
         S1 = `#S1-unstim log`, 
         S2 = `#S2-unstim log`, 
         SEB = `#SEB-unstim log`) %>%
  filter(!is.na(CEFX) | !is.na(S1) | !is.na(S2) | !is.na(SEB)) %>%
  mutate(PatID_Studie1 = as.character(PatID_Studie1)) %>% 
  filter(!(ausschliessen == 1)) %>% 
  mutate(Studie1 = str_replace(Studie1, c("Pa-COVID-19"), "Pa-COVID")) %>% 
  mutate(PatID_Studie1 = paste(tolower(paste(substr(Studie1, 1, 2))), 
                               tolower(paste(substr(Studie1, (nchar(Studie1)-1), nchar(Studie1)), 
                                             PatID_Studie1, 
                                             sep = "")),
                               sep = "")) %>% 
  mutate(Timepoint = str_replace_all(Timepoint, c("1"="PI", "M2-4"="M3", "after month 5"="M5+", "W3-6"="W4", "W 2"="W2"))) %>% 
  mutate(Dexa = str_replace_all(Dexa, c("1" = "D+", "0" = "D-", "3" = "mild")))


# meta data
meta <- read_excel("../metadata_all_patients_2022 01 07 CT.xlsx") %>%
  select(contains("sanity"),
         contains("Studie 1"),
         contains("Alter / Geschaetztes Alter bei Einschluss gr 3 Jahre"),
         contains("Geschlecht bei der Geburt"),
         contains("Dexamethason"),
         contains("Immunosuppression"),
         contains("Bemerkung"),
         contains("Start Dexa"),
         contains("Ende Dexa")) %>% 
  rename(PatID_Studie1 = `PatID Studie 1`, 
         Age = `Alter / Geschaetztes Alter bei Einschluss gr 3 Jahre`, 
         Sex = `Geschlecht bei der Geburt` ,
         Studie1 = `Studie 1`,
         Dexa = Dexamethason) %>%
  mutate(PatID_Studie1 = as.character(PatID_Studie1)) %>% 
  filter(!grepl(.$Bemerkung, pattern = "Immun", ignore.case = T)) %>% 
  mutate(PatID_Studie1 = str_replace(PatID_Studie1, c("C19-CB-"), "")) %>%
  mutate(PatID_Studie1 = as.character(as.numeric(PatID_Studie1))) %>% 
  mutate(Studie1 = str_replace(Studie1, c("Pa-COVID-19"), "Pa-COVID")) %>% 
  mutate(PatID_Studie1 = paste(tolower(paste(substr(Studie1, 1, 2))), 
                               tolower(paste(substr(Studie1, (nchar(Studie1)-1), nchar(Studie1)), 
                                             PatID_Studie1, 
                                             sep = "")),
                               sep = "")) %>% 
  mutate(Dexa = str_replace_all(Dexa, c("1" = "D+", "0" = "D-", "3" = "mild")))

# serology
sero <- read_excel("../all serology 2021 12 and 10 sanity checks completed +clinical.xlsx") %>% 
  select(contains("Studie 1"),
         contains("Entnahmedatum"),
         contains("Tag PSO"),
         contains("Bemerkung"),
         contains("Zeitraum"),
         contains("IgG"),
         contains("Dexa"),
         contains("ausschliessen (Immunsuppression, other)")) %>% 
  rename(PatID_Studie1 = `PatID Studie 1 von all results serology 2021 12 and 10 sanity checks completed`,
         Studie1 = `Studie 1 von all results serology 2021 12 and 10 sanity checks completed`,
         IgG = `IgG Value BAU/ml >=7.1 reactive`,
         TagPSO = `Tag PSO`, 
         Timepoint = Zeitraum, 
         Dexa = `Dexamethason von all results serology 2021 12 and 10 sanity checks completed`,
         ausschliessen_imm = `ausschliessen (Immunsuppression, other)`) %>% 
  mutate(ausschliessen_imm = replace_na(ausschliessen_imm, 0)) %>%
  mutate(PatID_Studie1 = str_replace(PatID_Studie1, c("C19-CB-"), "")) %>% 
  mutate(PatID_Studie1 = as.character(as.numeric(PatID_Studie1))) %>% 
  mutate(IgG = as.numeric(str_replace(IgG, c(","), "\\."))) %>% 
  filter(!ausschliessen_imm == 1) %>% 
  mutate(Studie1 = str_replace(Studie1, c("Pa-COVID-19"), "Pa-COVID")) %>% 
  mutate(PatID_Studie1 = str_replace(PatID_Studie1, c("C19-CB-"), "")) %>%
  mutate(PatID_Studie1 = as.character(as.numeric(PatID_Studie1))) %>% 
  mutate(PatID_Studie1 = paste(tolower(paste(substr(Studie1, 1, 2))), 
                               tolower(paste(substr(Studie1, (nchar(Studie1)-1), nchar(Studie1)), 
                                             PatID_Studie1, 
                                             sep = "")),
                               sep = "")) %>% 
  mutate(Dexa = str_replace_all(Dexa, c("1" = "D+", "0" = "D-", "3" = "mild")))

SRT <- c("S1", "S2")
strain <- c("B.1.1.7", "B.1.617.2")
level_order <- c('1', '0', '3')
```

```{r}
## How many patients have at least three time points in each measurement.
# facs_pat_3timepoints <- facs %>%
#   select(PatID_Studie1, Timepoint) %>%
#   distinct() %>%
#   group_by(PatID_Studie1) %>%
#   mutate(number_of_FACS_timepoints = n()) %>%
#   mutate(measured_at = paste0(Timepoint, collapse = ", ")) %>%
#   select(!Timepoint) %>%
#   distinct()
# write.table(facs_pat_3timepoints, "FACS_measurement_timepoints.tsv", row.names = F, quote = F, sep = "\t")
# 
# PNT_pat_3timepoints <- PNT %>%
#   select(PatID_Studie1, Days) %>%
#   distinct() %>%
#   group_by(PatID_Studie1) %>%
#   mutate(number_of_PNT_timepoints = n()) %>%
#   mutate(measured_at = paste0(Days, collapse = ", ")) %>%
#   select(!Days) %>%
#   distinct()
# write.table(PNT_pat_3timepoints, "PNT_measurement_timepoints.tsv", row.names = F, quote = F, sep = "\t")
# 
# sero_pat_3timepoints <- sero %>%
#   select(PatID_Studie1, Timepoint) %>%
#   distinct() %>%
#   group_by(PatID_Studie1) %>%
#   mutate(number_of_Sero_timepoint = n()) %>%
#   mutate(measured_at = paste0(Timepoint, collapse = ", ")) %>%
#   select(!Timepoint) %>%
#   distinct()
# write.table(sero_pat_3timepoints, "Serology_measurement_timepoints.tsv", row.names = F, quote = F, sep = "\t")

```

```{r tables_for_Lara}
# 
# # convert facs table to wide format for selected markers, for each patient
# facs_wide <- read_excel("../20220104 Mastertable FACS incl. dead and VC.xlsx") %>% 
#   select("Studie 1", 
#          "PatID Studie 1", 
#          "timepoints 2022", 
#          "Dexa", 
#          "Marker 1", 
#          "Marker 2", 
#          "#S1-unstim log", 
#          "#S2-unstim log", 
#          "ausschliessen") %>%
#   mutate(ausschliessen = replace_na(ausschliessen, 0)) %>% 
#   rename(Studie1 = `Studie 1`, 
#          PatID_Studie1 = `PatID Studie 1`, 
#          Timepoint = `timepoints 2022`,
#          Marker1 = `Marker 1`, 
#          Marker2 = `Marker 2`,
#          S1 = `#S1-unstim log`, 
#          S2 = `#S2-unstim log`) %>%
#   filter(!is.na(S1) | !is.na(S2)) %>%
#   mutate(PatID_Studie1 = as.character(PatID_Studie1)) %>% 
#   mutate(Timepoint = replace(Timepoint, PatID_Studie1=="435", "W 2")) %>% 
#   filter(!(PatID_Studie1 == "183" | 
#            PatID_Studie1 == "22" | 
#            PatID_Studie1 == "53" | 
#            PatID_Studie1 == "88" | 
#            PatID_Studie1 == "115" | 
#            PatID_Studie1 == "120" | 
#            PatID_Studie1 == "133" | 
#            PatID_Studie1 == "153")) %>% 
#   filter(!(ausschliessen == 1)) %>% 
#   mutate(Studie1 = str_replace(Studie1, c("Pa-COVID-19"), "Pa-COVID")) %>% 
#   mutate(PatID_Studie1_short = paste(tolower(paste(substr(Studie1, 1, 2))), 
#                                tolower(paste(substr(Studie1, (nchar(Studie1)-1), nchar(Studie1)), 
#                                              PatID_Studie1, 
#                                              sep = "")),
#                                sep = "")) %>% 
#   mutate(Timepoint = str_replace(Timepoint, c("1"), "PI")) %>% 
#   mutate(Timepoint = str_replace(Timepoint, c("M2-4"), "M3")) %>% 
#   mutate(Timepoint = str_replace(Timepoint, c("after month 5"), "M5+")) %>% 
#   mutate(Timepoint = str_replace(Timepoint, c("W3-6"), "W4")) %>% 
#   mutate(Timepoint = str_replace(Timepoint, c("W 2"), "W2"))
# 
# ### S1 ###
# 
# # 1 #
# CD40CD137 <- facs_wide %>% 
#   filter(Marker2 == "CD40L+ CD137+") %>% 
#   select(Studie1,
#          PatID_Studie1,
#          PatID_Studie1_short,
#          Dexa,
#          Timepoint,
#          Marker2,
#          S1) %>% 
#   group_by(Timepoint) %>%
#   mutate(row = row_number()) %>%
#   tidyr::pivot_wider(id_cols = c(PatID_Studie1, Studie1, PatID_Studie1_short, Dexa, Marker2), 
#                      names_from = Timepoint, 
#                      values_from = S1,
#                      values_fn = list) %>% 
#   mutate(Stimulation = rep("S1", nrow(.))) %>% 
#   mutate(PI = na_if(PI, c("NULL"))) %>%
#   mutate(W2 = na_if(W2, c("NULL"))) %>%
#   mutate(W4 = na_if(W4, c("NULL"))) %>%
#   mutate(M3 = na_if(M3, c("NULL"))) %>%
#   mutate(`M5+` = na_if(`M5+`, c("NULL")))
# 
# postvac <- c()
# for(i in 1:nrow(CD40CD137))
#   if(!is.null(CD40CD137$PI[[i]][1]))
#     postvac[i] <- CD40CD137$PI[[i]][1]
# CD40CD137$PI <-postvac
# 
# W2 <- c()
# for(i in 1:nrow(CD40CD137))
#   if(!is.null(CD40CD137$W2[[i]][1]))
#     W2[i] <- CD40CD137$W2[[i]][1]
# CD40CD137$W2 <-W2
# 
# W4 <- c()
# for(i in 1:nrow(CD40CD137))
#   if(!is.null(CD40CD137$W4[[i]][1]))
#     W4[i] <- CD40CD137$W4[[i]][1]
# CD40CD137$W4 <-W4
# 
# M3 <- c()
# for(i in 1:nrow(CD40CD137))
#   if(!is.null(CD40CD137$M3[[i]][1]))
#     M3[i] <- CD40CD137$M3[[i]][1]
# CD40CD137$M3 <-M3
# 
# M5 <- c()
# for(i in 1:nrow(CD40CD137))
#   if(!is.null(CD40CD137$`M5+`[[i]][1]))
#     M5[i] <- CD40CD137$`M5+`[[i]][1]
# CD40CD137$`M5+` <-M5
# 
# # 2 #
# CD40TNF <- facs_wide %>% 
#   filter(Marker2 == "CD40L+ TNF-a+") %>% 
#   select(Studie1,
#          PatID_Studie1,
#          PatID_Studie1_short,
#          Dexa,
#          Timepoint,
#          Marker2,
#          S1) %>% 
#   group_by(Timepoint) %>%
#   mutate(row = row_number()) %>%
#   tidyr::pivot_wider(id_cols = c(PatID_Studie1, Studie1, PatID_Studie1_short, Dexa, Marker2), 
#                      names_from = Timepoint, 
#                      values_from = S1,
#                      values_fn = list) %>% 
#   mutate(Stimulation = rep("S1", nrow(.))) %>% 
#   mutate(PI = na_if(PI, c("NULL"))) %>%
#   mutate(W2 = na_if(W2, c("NULL"))) %>%
#   mutate(W4 = na_if(W4, c("NULL"))) %>%
#   mutate(M3 = na_if(M3, c("NULL"))) %>%
#   mutate(`M5+` = na_if(`M5+`, c("NULL")))
# 
# postvac <- c()
# for(i in 1:nrow(CD40TNF))
#   if(!is.null(CD40TNF$PI[[i]][1]))
#     postvac[i] <- CD40TNF$PI[[i]][1]
# CD40TNF$PI <-postvac
# 
# W2 <- c()
# for(i in 1:nrow(CD40TNF))
#   if(!is.null(CD40TNF$W2[[i]][1]))
#     W2[i] <- CD40TNF$W2[[i]][1]
# CD40TNF$W2 <-W2
# 
# W4 <- c()
# for(i in 1:nrow(CD40TNF))
#   if(!is.null(CD40TNF$W4[[i]][1]))
#     W4[i] <- CD40TNF$W4[[i]][1]
# CD40TNF$W4 <-W4
# 
# M3 <- c()
# for(i in 1:nrow(CD40TNF))
#   if(!is.null(CD40TNF$M3[[i]][1]))
#     M3[i] <- CD40TNF$M3[[i]][1]
# CD40TNF$M3 <-M3
# 
# M5 <- c()
# for(i in 1:nrow(CD40TNF))
#   if(!is.null(CD40TNF$`M5+`[[i]][1]))
#     M5[i] <- CD40TNF$`M5+`[[i]][1]
# CD40TNF$`M5+` <-M5
# 
# 
# # 3 #
# CD40IL21 <- facs_wide %>% 
#   filter(Marker2 == "CD40L+ IL-21+") %>% 
#   select(Studie1,
#          PatID_Studie1,
#          PatID_Studie1_short,
#          Dexa,
#          Timepoint,
#          Marker2,
#          S1) %>% 
#   group_by(Timepoint) %>%
#   mutate(row = row_number()) %>%
#   tidyr::pivot_wider(id_cols = c(PatID_Studie1, Studie1, PatID_Studie1_short, Dexa, Marker2), 
#                      names_from = Timepoint, 
#                      values_from = S1,
#                      values_fn = list) %>% 
#   mutate(Stimulation = rep("S1", nrow(.))) %>% 
#   mutate(PI = na_if(PI, c("NULL"))) %>%
#   mutate(W2 = na_if(W2, c("NULL"))) %>%
#   mutate(W4 = na_if(W4, c("NULL"))) %>%
#   mutate(M3 = na_if(M3, c("NULL"))) %>%
#   mutate(`M5+` = na_if(`M5+`, c("NULL")))
# 
# postvac <- c()
# for(i in 1:nrow(CD40IL21))
#   if(!is.null(CD40IL21$PI[[i]][1]))
#     postvac[i] <- CD40IL21$PI[[i]][1]
# CD40IL21$PI <-postvac
# 
# W2 <- c()
# for(i in 1:nrow(CD40IL21))
#   if(!is.null(CD40IL21$W2[[i]][1]))
#     W2[i] <- CD40IL21$W2[[i]][1]
# CD40IL21$W2 <-W2
# 
# W4 <- c()
# for(i in 1:nrow(CD40IL21))
#   if(!is.null(CD40IL21$W4[[i]][1]))
#     W4[i] <- CD40IL21$W4[[i]][1]
# CD40IL21$W4 <-W4
# 
# M3 <- c()
# for(i in 1:nrow(CD40IL21))
#   if(!is.null(CD40IL21$M3[[i]][1]))
#     M3[i] <- CD40IL21$M3[[i]][1]
# CD40IL21$M3 <-M3
# 
# M5 <- c()
# for(i in 1:nrow(CD40IL21))
#   if(!is.null(CD40IL21$`M5+`[[i]][1]))
#     M5[i] <- CD40IL21$`M5+`[[i]][1]
# CD40IL21$`M5+` <-M5
# 
# # 4 #
# livecells <- facs_wide %>% 
#   filter(Marker2 == "live cells") %>% 
#   select(Studie1,
#          PatID_Studie1,
#          PatID_Studie1_short,
#          Dexa,
#          Timepoint,
#          Marker2,
#          S1) %>% 
#   group_by(Timepoint) %>%
#   mutate(row = row_number()) %>%
#   tidyr::pivot_wider(id_cols = c(PatID_Studie1, Studie1, PatID_Studie1_short, Dexa, Marker2), 
#                      names_from = Timepoint, 
#                      values_from = S1,
#                      values_fn = list) %>% 
#   mutate(Stimulation = rep("S1", nrow(.))) %>% 
#   mutate(PI = na_if(PI, c("NULL"))) %>%
#   mutate(W2 = na_if(W2, c("NULL"))) %>%
#   mutate(W4 = na_if(W4, c("NULL"))) %>%
#   mutate(M3 = na_if(M3, c("NULL"))) %>%
#   mutate(`M5+` = na_if(`M5+`, c("NULL")))
# 
# postvac <- c()
# for(i in 1:nrow(livecells))
#   if(!is.null(livecells$PI[[i]][1]))
#     postvac[i] <- livecells$PI[[i]][1]
# livecells$PI <-postvac
# 
# W2 <- c()
# for(i in 1:nrow(livecells))
#   if(!is.null(livecells$W2[[i]][1]))
#     W2[i] <- livecells$W2[[i]][1]
# livecells$W2 <-W2
# 
# W4 <- c()
# for(i in 1:nrow(livecells))
#   if(!is.null(livecells$W4[[i]][1]))
#     W4[i] <- livecells$W4[[i]][1]
# livecells$W4 <-W4
# 
# M3 <- c()
# for(i in 1:nrow(livecells))
#   if(!is.null(livecells$M3[[i]][1]))
#     M3[i] <- livecells$M3[[i]][1]
# livecells$M3 <-M3
# 
# M5 <- c()
# for(i in 1:nrow(livecells))
#   if(!is.null(livecells$`M5+`[[i]][1]))
#     M5[i] <- livecells$`M5+`[[i]][1]
# livecells$`M5+` <-M5
# 
# write.csv(CD40CD137, file = "../S1_CD40CD137.csv", row.names = F, quote = F)
# write.csv(CD40TNF, file = "../S1_CD40TNF.csv", row.names = F, quote = F)
# write.csv(CD40CD137, file = "../S1_CD40IL21.csv", row.names = F, quote = F)
# write.csv(CD40CD137, file = "../S1_livecells.csv", row.names = F, quote = F)
# 
# 

```

```{r S2}
# ### S2 ###
# 
# # 1 #
# CD40CD137 <- facs_wide %>% 
#   filter(Marker2 == "CD40L+ CD137+") %>% 
#   select(Studie1,
#          PatID_Studie1,
#          PatID_Studie1_short,
#          Dexa,
#          Timepoint,
#          Marker2,
#          S2) %>% 
#   group_by(Timepoint) %>%
#   mutate(row = row_number()) %>%
#   tidyr::pivot_wider(id_cols = c(PatID_Studie1, Studie1, PatID_Studie1_short, Dexa, Marker2), 
#                      names_from = Timepoint, 
#                      values_from = S2,
#                      values_fn = list) %>% 
#   mutate(Stimulation = rep("S2", nrow(.))) %>% 
#   mutate(PI = na_if(PI, c("NULL"))) %>%
#   mutate(W2 = na_if(W2, c("NULL"))) %>%
#   mutate(W4 = na_if(W4, c("NULL"))) %>%
#   mutate(M3 = na_if(M3, c("NULL"))) %>%
#   mutate(`M5+` = na_if(`M5+`, c("NULL")))
# 
# postvac <- c()
# for(i in 1:nrow(CD40CD137))
#   if(!is.null(CD40CD137$PI[[i]][1]))
#     postvac[i] <- CD40CD137$PI[[i]][1]
# CD40CD137$PI <-postvac
# 
# W2 <- c()
# for(i in 1:nrow(CD40CD137))
#   if(!is.null(CD40CD137$W2[[i]][1]))
#     W2[i] <- CD40CD137$W2[[i]][1]
# CD40CD137$W2 <-W2
# 
# W4 <- c()
# for(i in 1:nrow(CD40CD137))
#   if(!is.null(CD40CD137$W4[[i]][1]))
#     W4[i] <- CD40CD137$W4[[i]][1]
# CD40CD137$W4 <-W4
# 
# M3 <- c()
# for(i in 1:nrow(CD40CD137))
#   if(!is.null(CD40CD137$M3[[i]][1]))
#     M3[i] <- CD40CD137$M3[[i]][1]
# CD40CD137$M3 <-M3
# 
# M5 <- c()
# for(i in 1:nrow(CD40CD137))
#   if(!is.null(CD40CD137$`M5+`[[i]][1]))
#     M5[i] <- CD40CD137$`M5+`[[i]][1]
# CD40CD137$`M5+` <-M5
# 
# # 2 #
# CD40TNF <- facs_wide %>% 
#   filter(Marker2 == "CD40L+ TNF-a+") %>% 
#   select(Studie1,
#          PatID_Studie1,
#          PatID_Studie1_short,
#          Dexa,
#          Timepoint,
#          Marker2,
#          S2) %>% 
#   group_by(Timepoint) %>%
#   mutate(row = row_number()) %>%
#   tidyr::pivot_wider(id_cols = c(PatID_Studie1, Studie1, PatID_Studie1_short, Dexa, Marker2), 
#                      names_from = Timepoint, 
#                      values_from = S2,
#                      values_fn = list) %>% 
#   mutate(Stimulation = rep("S2", nrow(.))) %>% 
#   mutate(PI = na_if(PI, c("NULL"))) %>%
#   mutate(W2 = na_if(W2, c("NULL"))) %>%
#   mutate(W4 = na_if(W4, c("NULL"))) %>%
#   mutate(M3 = na_if(M3, c("NULL"))) %>%
#   mutate(`M5+` = na_if(`M5+`, c("NULL")))
# 
# postvac <- c()
# for(i in 1:nrow(CD40TNF))
#   if(!is.null(CD40TNF$PI[[i]][1]))
#     postvac[i] <- CD40TNF$PI[[i]][1]
# CD40TNF$PI <-postvac
# 
# W2 <- c()
# for(i in 1:nrow(CD40TNF))
#   if(!is.null(CD40TNF$W2[[i]][1]))
#     W2[i] <- CD40TNF$W2[[i]][1]
# CD40TNF$W2 <-W2
# 
# W4 <- c()
# for(i in 1:nrow(CD40TNF))
#   if(!is.null(CD40TNF$W4[[i]][1]))
#     W4[i] <- CD40TNF$W4[[i]][1]
# CD40TNF$W4 <-W4
# 
# M3 <- c()
# for(i in 1:nrow(CD40TNF))
#   if(!is.null(CD40TNF$M3[[i]][1]))
#     M3[i] <- CD40TNF$M3[[i]][1]
# CD40TNF$M3 <-M3
# 
# M5 <- c()
# for(i in 1:nrow(CD40TNF))
#   if(!is.null(CD40TNF$`M5+`[[i]][1]))
#     M5[i] <- CD40TNF$`M5+`[[i]][1]
# CD40TNF$`M5+` <-M5
# 
# 
# # 3 #
# CD40IL21 <- facs_wide %>% 
#   filter(Marker2 == "CD40L+ IL-21+") %>% 
#   select(Studie1,
#          PatID_Studie1,
#          PatID_Studie1_short,
#          Dexa,
#          Timepoint,
#          Marker2,
#          S2) %>% 
#   group_by(Timepoint) %>%
#   mutate(row = row_number()) %>%
#   tidyr::pivot_wider(id_cols = c(PatID_Studie1, Studie1, PatID_Studie1_short, Dexa, Marker2), 
#                      names_from = Timepoint, 
#                      values_from = S2,
#                      values_fn = list) %>% 
#   mutate(Stimulation = rep("S2", nrow(.))) %>% 
#   mutate(PI = na_if(PI, c("NULL"))) %>%
#   mutate(W2 = na_if(W2, c("NULL"))) %>%
#   mutate(W4 = na_if(W4, c("NULL"))) %>%
#   mutate(M3 = na_if(M3, c("NULL"))) %>%
#   mutate(`M5+` = na_if(`M5+`, c("NULL")))
# 
# postvac <- c()
# for(i in 1:nrow(CD40IL21))
#   if(!is.null(CD40IL21$PI[[i]][1]))
#     postvac[i] <- CD40IL21$PI[[i]][1]
# CD40IL21$PI <-postvac
# 
# W2 <- c()
# for(i in 1:nrow(CD40IL21))
#   if(!is.null(CD40IL21$W2[[i]][1]))
#     W2[i] <- CD40IL21$W2[[i]][1]
# CD40IL21$W2 <-W2
# 
# W4 <- c()
# for(i in 1:nrow(CD40IL21))
#   if(!is.null(CD40IL21$W4[[i]][1]))
#     W4[i] <- CD40IL21$W4[[i]][1]
# CD40IL21$W4 <-W4
# 
# M3 <- c()
# for(i in 1:nrow(CD40IL21))
#   if(!is.null(CD40IL21$M3[[i]][1]))
#     M3[i] <- CD40IL21$M3[[i]][1]
# CD40IL21$M3 <-M3
# 
# M5 <- c()
# for(i in 1:nrow(CD40IL21))
#   if(!is.null(CD40IL21$`M5+`[[i]][1]))
#     M5[i] <- CD40IL21$`M5+`[[i]][1]
# CD40IL21$`M5+` <-M5
# 
# # 4 #
# livecells <- facs_wide %>% 
#   filter(Marker2 == "live cells") %>% 
#   select(Studie1,
#          PatID_Studie1,
#          PatID_Studie1_short,
#          Dexa,
#          Timepoint,
#          Marker2,
#          S2) %>% 
#   group_by(Timepoint) %>%
#   mutate(row = row_number()) %>%
#   tidyr::pivot_wider(id_cols = c(PatID_Studie1, Studie1, PatID_Studie1_short, Dexa, Marker2), 
#                      names_from = Timepoint, 
#                      values_from = S2,
#                      values_fn = list) %>% 
#   mutate(Stimulation = rep("S2", nrow(.))) %>% 
#   mutate(PI = na_if(PI, c("NULL"))) %>%
#   mutate(W2 = na_if(W2, c("NULL"))) %>%
#   mutate(W4 = na_if(W4, c("NULL"))) %>%
#   mutate(M3 = na_if(M3, c("NULL"))) %>%
#   mutate(`M5+` = na_if(`M5+`, c("NULL")))
# 
# postvac <- c()
# for(i in 1:nrow(livecells))
#   if(!is.null(livecells$PI[[i]][1]))
#     postvac[i] <- livecells$PI[[i]][1]
# livecells$PI <-postvac
# 
# W2 <- c()
# for(i in 1:nrow(livecells))
#   if(!is.null(livecells$W2[[i]][1]))
#     W2[i] <- livecells$W2[[i]][1]
# livecells$W2 <-W2
# 
# W4 <- c()
# for(i in 1:nrow(livecells))
#   if(!is.null(livecells$W4[[i]][1]))
#     W4[i] <- livecells$W4[[i]][1]
# livecells$W4 <-W4
# 
# M3 <- c()
# for(i in 1:nrow(livecells))
#   if(!is.null(livecells$M3[[i]][1]))
#     M3[i] <- livecells$M3[[i]][1]
# livecells$M3 <-M3
# 
# M5 <- c()
# for(i in 1:nrow(livecells))
#   if(!is.null(livecells$`M5+`[[i]][1]))
#     M5[i] <- livecells$`M5+`[[i]][1]
# livecells$`M5+` <-M5
# 
# write.csv(CD40CD137, file = "../S2_CD40CD137.csv", row.names = F, quote = F)
# write.csv(CD40TNF, file = "../S2_CD40TNF.csv", row.names = F, quote = F)
# write.csv(CD40CD137, file = "../S2_CD40IL21.csv", row.names = F, quote = F)
# write.csv(CD40CD137, file = "../S2_livecells.csv", row.names = F, quote = F)
```

```{r Timeseries T-cells, PNT and IgG of patients with multiple measurements}
## SRT discrete time points
## CD4
for(i in SRT)
  {
    print(
      facs %>%
        filter(Marker1 == "CD4") %>%
        filter(!(Timepoint == "PI" | Timepoint == "VC")) %>% 
        filter(Marker2 == "CD40L+ CD137+" | Marker2 ==  "CD40L+ TNF-a+" | Marker2 == "CD40L+ IL-21+") %>% 
        #left_join(SRT_2_tp, ., by = "PatID_Studie1") %>% 
      ggplot(., aes(x = factor(Timepoint, 
                               levels = c('W2', 'W4', 'M3', 
                                          'M5+')), 
                    y = !!sym(i), 
                    colour = factor(Dexa))) +
        theme(axis.text.x = element_text(angle = 90)) +
        geom_jitter(width = 0.1, alpha = 0.5) +
        scale_y_log10() +
        labs(col = "Dexa") + 
        #geom_boxplot(aes(fill = factor(Dexa)), width = 0.5, 
        #             colour = "gray47", alpha = 0.5, outlier.shape = NA) +
        scale_color_manual(breaks = c("D+", "D-", "mild"),
                          values = c("orangered", "blue", "green3")) +
        scale_fill_manual(breaks = c("D+", "D-", "mild"),
                          values = c("orangered", "blue", "green3")) +
        facet_wrap(~factor(Marker2, levels = c("CD40L+ CD137+",
                                               "CD40L+ TNF-a+","CD40L+ IL-21+")),
                   scales = "free", ncol = 3) +
        geom_smooth(method = "lm", aes(group = factor(Dexa)), alpha = 0.7, 
                    se = F, size = 0.4) +
        xlab("Time point") +
        ggtitle(paste0(i, " progression in CD4 cells")) +
        theme_bw() +
        theme(strip.background =element_rect(fill="aliceblue")))
  ggsave(paste0("MSimages/", i, " progressionCD4.png"), width = 20, height = 10, units = "cm")
}

## CD8
## markers don't exist for CD8

## SRT TagPSO
## CD4

for(i in SRT)
{
  print(
    facs %>%
      filter(Marker1 == "CD4") %>%
      filter(!(Timepoint == "PI" | Timepoint == "VC")) %>% 
      filter(Marker2 == "CD40L+ CD137+" | Marker2 ==  "CD40L+ TNF-a+" | Marker2 == "CD40L+ IL-21+") %>% 
      #left_join(SRT_2_tp, ., by = "PatID_Studie1") %>% 
    ggplot(aes(x = TagPSO, y = !!sym(i), 
                  colour = factor(Dexa))) +
      geom_point(alpha = 0.5) +
      labs(col = "Dexa") +
      scale_y_log10() +
      scale_color_manual(breaks = c("D+", "D-", "mild"),
                          values = c("orangered", "blue", "green3")) +
      facet_wrap(~factor(Marker2, levels = c("CD40L+ CD137+",
                                             "CD40L+ TNF-a+","CD40L+ IL-21+")),
                 scales = "free", ncol = 3) +
      theme(strip.background =element_rect(fill="aliceblue")) +
      geom_smooth(method = "lm", aes(group = factor(Dexa)), alpha = 0.7, 
                  se = F, size = 0.4) +
      xlab("Days PSO") +
      ggtitle(paste0(i, " progression in CD4 cells")) +
      theme(axis.text.x = element_text(angle = 90)) +
      theme_bw() +
      theme(strip.background =element_rect(fill="aliceblue")))
  ggsave(paste0("MSimages/", i, " progressionCD4_DaysPSO.png"), width = 20, height = 10, units = "cm")
}

## breakup dexa groups and join by patients and have the fitted line
# trimepoints
marker.labels <- c(`CD40L+ CD137+`="CD40L+ CD137+",`CD40L+ TNF-a+`="CD40L+ TNF-a+",`CD40L+ IL-21+`="CD40L+ IL-21+")
dexa.labels <- c(`1` = "D+", `0` = "D-", `3` = "mild")

for(i in SRT)
{  
  print(
    facs %>%
      filter(Marker1 == "CD4") %>%
      filter(!(Timepoint == "PI" | Timepoint == "VC")) %>% 
      filter(Marker2 == "CD40L+ CD137+" | Marker2 ==  "CD40L+ TNF-a+" | Marker2 == "CD40L+ IL-21+") %>% 
      #left_join(SRT_2_tp, ., by = "PatID_Studie1") %>% 
    ggplot(., aes(x = factor(Timepoint, 
                             levels = c('W2', 'W4', 'M3', 
                                        'M5+')), 
                  y = !!sym(i), 
                  colour = factor(Dexa),
                  group = factor(PatID_Studie1))) +
      geom_point(position = position_dodge(0.4), alpha = 0.5) +
      #geom_jitter(width = 0.1, alpha = 0.2) +
      scale_y_log10() +
      labs(col = "Dexa") + 
      #geom_boxplot(aes(fill = factor(Dexa)), width = 0.5, 
      #             colour = "gray47", alpha = 0.5, outlier.shape = NA) +
      scale_color_manual(breaks = c("D+", "D-", "mild"),
                          values = c("orangered", "blue", "green3")) +
      scale_fill_manual(breaks = c("D+", "D-", "mild"),
                          values = c("orangered", "blue", "green3")) +
      geom_smooth(method = "lm", aes(group = factor(Dexa)), alpha = 0.7, 
                  se = F, size = 0.4) + 
      geom_line(position = position_dodge(0.4), aes(group = factor(PatID_Studie1)), 
                alpha = 0.5, size = 0.2)+
      facet_grid(factor(Marker2, levels = c("CD40L+ CD137+",
                                             "CD40L+ TNF-a+","CD40L+ IL-21+")) ~ factor(Dexa, levels = c('D+', 'D-', 'mild')),
                 #ncol = 3,
                 labeller = labeller(Marker2 = as_labeller(marker.labels),
                                     Dexa = as_labeller(dexa.labels)),
                 scales = "free") +
      xlab("Time point") +
      ggtitle(paste0(i, " progression in CD4 cells")) +
      theme_bw() +
      theme(strip.background =element_rect(fill="aliceblue")))
  ggsave(paste0("MSimages/", i, " progressionCD4_byDexa.png"), width = 20, height = 15, units = "cm")
}

for(i in SRT)
{  
  print(
    facs %>%
      filter(Marker1 == "CD4") %>%
      filter(!(Timepoint == "PI" | Timepoint == "VC")) %>% 
      filter(Marker2 == "CD40L+ CD137+" | Marker2 ==  "CD40L+ TNF-a+" | Marker2 == "CD40L+ IL-21+") %>% 
      #left_join(SRT_2_tp, ., by = "PatID_Studie1") %>% 
    ggplot(., aes(x = TagPSO,y = !!sym(i), 
                  colour = factor(Dexa),
                  group = factor(PatID_Studie1))) +
      theme(axis.text.x = element_text(angle = 90)) +
      geom_point(position = position_dodge(0.4), alpha = 0.5) +
      #geom_jitter(width = 0.1, alpha = 0.2) +
      scale_y_log10() +
      labs(col = "Dexa") + 
      #geom_boxplot(aes(fill = factor(Dexa)), width = 0.5, 
      #             colour = "gray47", alpha = 0.5, outlier.shape = NA) +
      scale_color_manual(breaks = c("D+", "D-", "mild"),
                          values = c("orangered", "blue", "green3")) +
      scale_fill_manual(breaks = c("D+", "D-", "mild"),
                          values = c("orangered", "blue", "green3")) +
      geom_smooth(method = "lm", aes(group = factor(Dexa)), alpha = 0.7, 
                  se = F, size = 0.5) +
       geom_line(position = position_dodge(0.4), aes(group = factor(PatID_Studie1)), 
                alpha = 0.5, size = 0.2)+
      facet_grid(factor(Marker2, levels = c("CD40L+ CD137+",
                                             "CD40L+ TNF-a+","CD40L+ IL-21+")) ~ factor(Dexa, levels = c('D+', 'D-', 'mild')),
                 #ncol = 3,
                 labeller = labeller(Marker2 = as_labeller(marker.labels),
                                     Dexa = as_labeller(dexa.labels)),
                 scales = "free") +
      xlab("Days PSO") +
      ggtitle(paste0(i, " progression in CD4 cells")) +
      theme_bw() +
      theme(strip.background =element_rect(fill="aliceblue")))
  ggsave(paste0("MSimages/", i, " progressionCD4_DaysPSO_byDexa.png"), width = 20, height = 15, units = "cm")
}
```

```{r PNT time series}
## PNT
# B.1.1.7
i = "B.1.1.7"
print(
    PNT %>%
      filter(!(Timepoint == "PI" | Timepoint == "VC")) %>%
      filter(exclude_B.1.1.7 == 0) %>% 
      #mutate(exclude_col := "{exclude}_{{ i }}")
      #filter("{exclude}_{{ i }}" == 0) %>% 
      #left_join(PNT_2_tp, ., by = "PatID_Studie1") %>% 
      ggplot(., aes(x = factor(Timepoint, 
                             levels = c('W2', 'W4', 'M3', 
                                        'M5+')), 
                  y = !!sym(i), 
                  colour = factor(Dexa))) +
      geom_jitter(width = 0.1, alpha = 0.5) +
      labs(col = "Dexa") +
      scale_y_log10() +
      #geom_boxplot(aes(fill = factor(Dexa)), width = 0.5, 
      #             colour = "gray47", alpha = 0.5, outlier.shape = NA) +
      scale_color_manual(breaks = c("D+", "D-", "mild"),
                          values = c("orangered", "blue", "green3")) +
      scale_fill_manual(breaks = c("D+", "D-", "mild"),
                          values = c("orangered", "blue", "green3")) +
      # facet_wrap(~factor(Marker2, levels = c("CD40L+ CD137+","CD40L+ GrzB+",
      #                                        "CD40L+ IFN-g+","CD40L+ IL-21+",
      #                                        "CD40L+ TNF-a+","CD137+ GrzB+",
      #                                        "CD137+ IFN-g+","CD137+ IL-21+",
      #                                        "CD137+ TNF-a+","CD137+ GrzB-")),
      #            scales = "free") +
      # facet_grid(. ~ factor(Dexa, levels = c('1', '0', '3')),
                 #ncol = 3,
                 #labeller = labeller(Dexa = as_labeller(dexa.labels))) +
      geom_smooth(method = "lm", aes(group = factor(Dexa)), alpha = 0.7, 
                  se = F, size = 0.4) +
      xlab("Time point") +
      ggtitle(paste0(i, " neutralisation progression")) +
      theme_bw() +
      theme(strip.background =element_rect(fill="aliceblue")))
ggsave(paste0("MSimages/", i, " neutralisation progression.png"), width = 20, height = 15, units = "cm")

i = "B.1.617.2"
print(
    PNT %>%
      filter(!(Timepoint == "PI" | Timepoint == "VC")) %>%
      filter(exclude_B.1.617.2 == 0) %>% 
      #mutate(exclude_col := "{exclude}_{{ i }}")
      #filter("{exclude}_{{ i }}" == 0) %>% 
      #left_join(PNT_2_tp, ., by = "PatID_Studie1") %>% 
      ggplot(., aes(x = factor(Timepoint, 
                             levels = c('W2', 'W4', 'M3', 
                                        'M5+')), 
                  y = !!sym(i), 
                  colour = factor(Dexa))) +
      geom_jitter(width = 0.1, alpha = 0.5) +
      labs(col = "Dexa") +
      scale_y_log10() +
      #geom_boxplot(aes(fill = factor(Dexa)), width = 0.5, 
      #             colour = "gray47", alpha = 0.5, outlier.shape = NA) +
      scale_color_manual(breaks = c("D+", "D-", "mild"),
                          values = c("orangered", "blue", "green3")) +
      scale_fill_manual(breaks = c("D+", "D-", "mild"),
                          values = c("orangered", "blue", "green3")) +
      # facet_wrap(~factor(Marker2, levels = c("CD40L+ CD137+","CD40L+ GrzB+",
      #                                        "CD40L+ IFN-g+","CD40L+ IL-21+",
      #                                        "CD40L+ TNF-a+","CD137+ GrzB+",
      #                                        "CD137+ IFN-g+","CD137+ IL-21+",
      #                                        "CD137+ TNF-a+","CD137+ GrzB-")),
      #            scales = "free") +
      # facet_grid(. ~ factor(Dexa, levels = c('1', '0', '3')),
                 #ncol = 3,
                 #labeller = labeller(Dexa = as_labeller(dexa.labels))) +
      geom_smooth(method = "lm", aes(group = factor(Dexa)), alpha = 0.7, 
                  se = F, size = 0.4) +
      xlab("Time point") +
      ggtitle(paste0(i, " neutralisation progression")) +
      theme_bw() +
      theme(strip.background =element_rect(fill="aliceblue")))
ggsave(paste0("MSimages/", i, " neutralisation progression.png"), width = 20, height = 15, units = "cm")

i = "B.1.1.7"
print(
    PNT %>%
      filter(!(Timepoint == "PI" | Timepoint == "VC")) %>% 
      filter(exclude_B.1.1.7 == 0) %>% 
      #left_join(PNT_2_tp, ., by = "PatID_Studie1") %>% 
      ggplot(., aes(x = TagPSO, y = !!sym(i), 
                  colour = factor(Dexa))) +
      geom_jitter(width = 0.1, alpha = 0.5) +
      labs(col = "Dexa") +
      scale_y_log10() +
      #geom_boxplot(aes(fill = factor(Dexa)), width = 0.5, 
      #             colour = "gray47", alpha = 0.5, outlier.shape = NA) +
      scale_color_manual(breaks = c("D+", "D-", "mild"),
                          values = c("orangered", "blue", "green3")) +
      scale_fill_manual(breaks = c("D+", "D-", "mild"),
                          values = c("orangered", "blue", "green3")) +
      # facet_wrap(~factor(Marker2, levels = c("CD40L+ CD137+","CD40L+ GrzB+",
      #                                        "CD40L+ IFN-g+","CD40L+ IL-21+",
      #                                        "CD40L+ TNF-a+","CD137+ GrzB+",
      #                                        "CD137+ IFN-g+","CD137+ IL-21+",
      #                                        "CD137+ TNF-a+","CD137+ GrzB-")),
      #            scales = "free") +
      # facet_wrap(. ~ factor(Dexa, levels = c('D+', 'D-', 'mild')),
      #            #ncol = 3,
      #            scales = "free",
      #            labeller = labeller(Dexa = as_labeller(dexa.labels))) +
      geom_smooth(method = "lm", aes(group = factor(Dexa)), alpha = 0.7, 
                  se = F, size = 0.4) +
      xlab("Days PSO") +
      ggtitle(paste0(i, " neutralisation progression")) +
      theme_bw() +
      theme(strip.background =element_rect(fill="aliceblue")))
ggsave(paste0("MSimages/", i, " neutralisation progression DaysPSO.png"), width = 20, height = 15, units = "cm")
  
i = "B.1.617.2"
print(
    PNT %>%
      filter(!(Timepoint == "PI" | Timepoint == "VC")) %>%
      filter(exclude_B.1.617.2 == 0) %>% 
      #left_join(PNT_2_tp, ., by = "PatID_Studie1") %>% 
      ggplot(., aes(x = TagPSO, y = !!sym(i), 
                  colour = factor(Dexa))) +
      geom_jitter(width = 0.1, alpha = 0.5) +
      labs(col = "Dexa") +
      scale_y_log10() +
      #geom_boxplot(aes(fill = factor(Dexa)), width = 0.5, 
      #             colour = "gray47", alpha = 0.5, outlier.shape = NA) +
      scale_color_manual(breaks = c("D+", "D-", "mild"),
                          values = c("orangered", "blue", "green3")) +
      scale_fill_manual(breaks = c("D+", "D-", "mild"),
                          values = c("orangered", "blue", "green3")) +
      # facet_wrap(~factor(Marker2, levels = c("CD40L+ CD137+","CD40L+ GrzB+",
      #                                        "CD40L+ IFN-g+","CD40L+ IL-21+",
      #                                        "CD40L+ TNF-a+","CD137+ GrzB+",
      #                                        "CD137+ IFN-g+","CD137+ IL-21+",
      #                                        "CD137+ TNF-a+","CD137+ GrzB-")),
      #            scales = "free") +
      # facet_wrap(. ~ factor(Dexa, levels = c('D+', 'D-', 'mild')),
      #            #ncol = 3,
      #            scales = "free",
      #            labeller = labeller(Dexa = as_labeller(dexa.labels))) +
      geom_smooth(method = "lm", aes(group = factor(Dexa)), alpha = 0.7, 
                  se = F, size = 0.4) +
      xlab("Days PSO") +
      ggtitle(paste0(i, " neutralisation progression")) +
      theme_bw() +
      theme(strip.background =element_rect(fill="aliceblue")))
ggsave(paste0("MSimages/", i, " neutralisation progression DaysPSO.png"), width = 20, height = 15, units = "cm")

## PNT separated by dexa and joined by patients

i = "B.1.1.7"
print(
    PNT %>%
      filter(!(Timepoint == "PI" | Timepoint == "VC")) %>% 
      filter(exclude_B.1.1.7 == 0) %>% 
      ggplot(aes(x = factor(Timepoint, 
                            levels = c('W2', 'W4', 'M3', 
                                          'M5+')), 
                 y = !!sym(i), 
                 colour = factor(Dexa),
                 group = factor(PatID_Studie1))) +
        labs(col = "Dexa") +
        theme(axis.text.x = element_text(angle = 90)) +
        #geom_jitter(width = 0.1, alpha = 0.2) +
        geom_point(position = position_dodge(0.4), alpha = 0.5) +
        scale_y_log10() +
        #geom_boxplot(aes(fill = factor(Dexa)), width = 0.5, 
        #             colour = "gray47", alpha = 0.5, outlier.shape = NA) +
        scale_color_manual(breaks = c("D+", "D-", "mild"),
                          values = c("orangered", "blue", "green3")) +
        scale_fill_manual(breaks = c("D+", "D-", "mild"),
                          values = c("orangered", "blue", "green3")) +
        # facet_wrap(~factor(Marker2, levels = c("CD40L+ CD137+","CD40L+ GrzB+",
        #                                        "CD40L+ IFN-g+","CD40L+ IL-21+",
        #                                        "CD40L+ TNF-a+","CD137+ GrzB+",
        #                                        "CD137+ IFN-g+","CD137+ IL-21+",
        #                                        "CD137+ TNF-a+","CD137+ GrzB-")),
        #            scales = "free") +
        facet_wrap(. ~ factor(Dexa, levels = c('D+', 'D-', 'mild')),
                 ncol = 3,
                 scales = "free",
                 labeller = labeller(Dexa = as_labeller(dexa.labels))) +
        geom_smooth(method = "lm", aes(group = factor(Dexa)), alpha = 0.7, 
                  se = F, size = 0.7) +
        geom_line(position = position_dodge(0.4), 
                  aes(group = factor(PatID_Studie1)), alpha = 0.8, 
                  size = 0.2) +
        xlab("Time point") +
        ggtitle(paste0(i, " neutralisation progression")) +
        theme_bw() +
        #theme(legend.position = "none") +
        theme(strip.background =element_rect(fill="aliceblue")))
ggsave(paste0("MSimages/", i, " neutralisation progression DaysPSO byPatient.png"), width = 20, height = 10, units = "cm")

i = "B.1.617.2"
print(
    PNT %>%
      filter(!(Timepoint == "PI" | Timepoint == "VC")) %>% 
      filter(exclude_B.1.617.2 == 0) %>% 
      ggplot(aes(x = factor(Timepoint, 
                            levels = c('W2', 'W4', 'M3', 
                                          'M5+')), 
                 y = !!sym(i), 
                 colour = factor(Dexa),
                 group = factor(PatID_Studie1))) +
        labs(col = "Dexa") +
        theme(axis.text.x = element_text(angle = 90)) +
        #geom_jitter(width = 0.1, alpha = 0.2) +
        geom_point(position = position_dodge(0.4), alpha = 0.5) +
        scale_y_log10() +
        #geom_boxplot(aes(fill = factor(Dexa)), width = 0.5, 
        #             colour = "gray47", alpha = 0.5, outlier.shape = NA) +
        scale_color_manual(breaks = c("D+", "D-", "mild"),
                          values = c("orangered", "blue", "green3")) +
        scale_fill_manual(breaks = c("D+", "D-", "mild"),
                          values = c("orangered", "blue", "green3")) +
        # facet_wrap(~factor(Marker2, levels = c("CD40L+ CD137+","CD40L+ GrzB+",
        #                                        "CD40L+ IFN-g+","CD40L+ IL-21+",
        #                                        "CD40L+ TNF-a+","CD137+ GrzB+",
        #                                        "CD137+ IFN-g+","CD137+ IL-21+",
        #                                        "CD137+ TNF-a+","CD137+ GrzB-")),
        #            scales = "free") +
        facet_wrap(. ~ factor(Dexa, levels = c('D+', 'D-', 'mild')),
                 ncol = 3,
                 scales = "free",
                 labeller = labeller(Dexa = as_labeller(dexa.labels))) +
        geom_smooth(method = "lm", aes(group = factor(Dexa)), alpha = 0.7, 
                  se = F, size = 0.7) +
        geom_line(position = position_dodge(0.4), 
                  aes(group = factor(PatID_Studie1)), alpha = 0.8, 
                  size = 0.2) +
        xlab("Time point") +
        ggtitle(paste0(i, " neutralisation progression")) +
        theme_bw() +
        #theme(legend.position = "none") +
        theme(strip.background =element_rect(fill="aliceblue")))
ggsave(paste0("MSimages/", i, " neutralisation progression DaysPSO byPatients.png"), width = 20, height = 10, units = "cm")


```

```{r IgG time series}
sero %>%
  filter(!(Timepoint == "PI" | Timepoint == "VC")) %>% 
  ggplot(., aes(x = factor(Timepoint, 
                           levels = c('W2', 'W4', 'M3', 
                                      'M5+')), 
                y = IgG, 
                colour = factor(Dexa))) +
    theme(axis.text.x = element_text(angle = 90)) +
    geom_jitter(width = 0.1, alpha = 0.5) +
    labs(col = "Dexa") +
    scale_y_log10() +
    #geom_boxplot(aes(fill = factor(Dexa)), width = 0.5, 
    #             colour = "gray47", alpha = 0.5, outlier.shape = NA) +
    scale_color_manual(breaks = c("D+", "D-", "mild"),
                          values = c("orangered", "blue", "green3")) +
    scale_fill_manual(breaks = c("D+", "D-", "mild"),
                          values = c("orangered", "blue", "green3")) +
    # facet_wrap(~factor(Marker2, levels = c("CD40L+ CD137+","CD40L+ GrzB+",
    #                                        "CD40L+ IFN-g+","CD40L+ IL-21+",
    #                                        "CD40L+ TNF-a+","CD137+ GrzB+",
    #                                        "CD137+ IFN-g+","CD137+ IL-21+",
    #                                        "CD137+ TNF-a+","CD137+ GrzB-")),
    #            scales = "free") +
    geom_smooth(method = "lm", aes(group = factor(Dexa)), alpha = 0.7, 
                se = F, size = 0.4) +
    xlab("Time point") +
    ggtitle("IgG progression") +
    theme_bw() +
    theme(strip.background =element_rect(fill="aliceblue"))
ggsave(paste0("MSimages/IgG progression.png"), width = 20, height = 15, units = "cm")


sero %>%
  filter(!(Timepoint == "PI" | Timepoint == "VC")) %>% 
  ggplot(aes(x = as.numeric(TagPSO), 
                y = IgG, 
                colour = factor(Dexa))) +
    theme(axis.text.x = element_text(angle = 90)) +
    geom_jitter(width = 0.1, alpha = 0.5) +
    labs(col = "Dexa") +
    scale_y_log10() +
    #geom_boxplot(aes(fill = factor(Dexa)), width = 0.5, 
    #             colour = "gray47", alpha = 0.5, outlier.shape = NA) +
    scale_color_manual(breaks = c("D+", "D-", "mild"),
                          values = c("orangered", "blue", "green3")) +
    scale_fill_manual(breaks = c("D+", "D-", "mild"),
                          values = c("orangered", "blue", "green3")) +
    # facet_wrap(~factor(Marker2, levels = c("CD40L+ CD137+","CD40L+ GrzB+",
    #                                        "CD40L+ IFN-g+","CD40L+ IL-21+",
    #                                        "CD40L+ TNF-a+","CD137+ GrzB+",
    #                                        "CD137+ IFN-g+","CD137+ IL-21+",
    #                                        "CD137+ TNF-a+","CD137+ GrzB-")),
    #            scales = "free") +
    geom_smooth(method = "lm", aes(group = factor(Dexa)), alpha = 0.7, 
                se = F, size = 0.4) +
    xlab("Days PSO") +
    ggtitle("IgG progression") +
    theme_bw() +
    theme(strip.background =element_rect(fill="aliceblue"))
ggsave(paste0("MSimages/IgG progression DaysPSO.png"), width = 20, height = 15, units = "cm")


sero %>%
  filter(!(Timepoint == "PI" | Timepoint == "VC")) %>% 
  ggplot(aes(x = factor(Timepoint, 
                           levels = c('W2', 'W4', 'M3', 
                                      'M5+')), 
             y = IgG, 
             colour = factor(Dexa),
             group = factor(PatID_Studie1))) +
    theme(axis.text.x = element_text(angle = 90)) +
    #geom_jitter(width = 0.1, alpha = 0.2) +
    geom_point(position = position_dodge(0.4), alpha = 0.5) +
    labs(col = "Dexa") +
    scale_y_log10() +
    #geom_boxplot(aes(fill = factor(Dexa)), width = 0.5, 
    #             colour = "gray47", alpha = 0.5, outlier.shape = NA) +
    scale_color_manual(breaks = c("D+", "D-", "mild"),
                          values = c("orangered", "blue", "green3")) +
    scale_fill_manual(breaks = c("D+", "D-", "mild"),
                          values = c("orangered", "blue", "green3")) +
    # facet_wrap(~factor(Marker2, levels = c("CD40L+ CD137+","CD40L+ GrzB+",
    #                                        "CD40L+ IFN-g+","CD40L+ IL-21+",
    #                                        "CD40L+ TNF-a+","CD137+ GrzB+",
    #                                        "CD137+ IFN-g+","CD137+ IL-21+",
    #                                        "CD137+ TNF-a+","CD137+ GrzB-")),
    #            scales = "free") +
    facet_wrap(. ~ factor(Dexa, levels = c('1', '0', '3')),
                 ncol = 3,
               scales = "free",
                 labeller = labeller(Dexa = as_labeller(dexa.labels))) +
    geom_smooth(method = "lm", aes(group = factor(Dexa)), alpha = 0.7, 
                  se = F, size = 0.7) +
    geom_line(position = position_dodge(0.4), aes(group = factor(PatID_Studie1)), alpha = 0.5, 
              size = 0.2) +
    xlab("Time point") +
    ggtitle("IgG progression") +
    theme_bw() +
    #theme(legend.position = "none") +
    theme(strip.background =element_rect(fill="aliceblue"))
ggsave(paste0("MSimages/IgG progression byDexa byPatient.png"), width = 20, height = 15, units = "cm")


sero %>%
  filter(!(Timepoint == "PI" | Timepoint == "VC")) %>% 
  ggplot(aes(x = as.numeric(TagPSO), 
             y = IgG, 
             colour = factor(Dexa),
             group = factor(PatID_Studie1))) +
    theme(axis.text.x = element_text(angle = 90)) +
    #geom_jitter(width = 0.1, alpha = 0.2) +
    geom_point(alpha = 0.5) +
    labs(col = "Dexa") +
    scale_y_log10() +
    #geom_boxplot(aes(fill = factor(Dexa)), width = 0.5, 
    #             colour = "gray47", alpha = 0.5, outlier.shape = NA) +
    scale_color_manual(breaks = c("D+", "D-", "mild"),
                          values = c("orangered", "blue", "green3")) +
    scale_fill_manual(breaks = c("D+", "D-", "mild"),
                          values = c("orangered", "blue", "green3")) +
    # facet_wrap(~factor(Marker2, levels = c("CD40L+ CD137+","CD40L+ GrzB+",
    #                                        "CD40L+ IFN-g+","CD40L+ IL-21+",
    #                                        "CD40L+ TNF-a+","CD137+ GrzB+",
    #                                        "CD137+ IFN-g+","CD137+ IL-21+",
    #                                        "CD137+ TNF-a+","CD137+ GrzB-")),
    #            scales = "free") +
    facet_wrap(. ~ factor(Dexa, levels = c('D+', 'D-', 'mild')),
                 ncol = 3,
               scales = "free",
                 labeller = labeller(Dexa = as_labeller(dexa.labels))) +
    geom_smooth(method = "lm", aes(group = factor(Dexa)), alpha = 0.7, 
                  se = F, size = 0.7) +
    geom_line(#position = position_dodge(0.4), 
              aes(group = factor(PatID_Studie1)), alpha = 0.5, 
              size = 0.2) +
    xlab("Days PSO") +
    ggtitle("IgG progression") +
    theme_bw() +
    #theme(legend.position = "none") +
    theme(strip.background =element_rect(fill="aliceblue"))
ggsave(paste0("MSimages/IgG progression DaysPSO byDexa byPatient.png"), width = 20, height = 15, units = "cm")

```

```{r Association of IgG and PNT at the respective timepoints}

Sero_PNT <- sero %>% 
  select(PatID_Studie1, Dexa, Timepoint, IgG) %>% 
  full_join(., PNT)

# IgG vs B.1.1.7

Sero_PNT %>% 
  filter(!Timepoint == "PI") %>% 
  filter(!(Timepoint == "W2" | Timepoint == "W4")) %>% 
  ggplot(aes(x = B.1.1.7, y = IgG)) +
  geom_point(alpha = 0.7, aes(colour = factor(Dexa))) +
  labs(col = "Dexa") +
  scale_y_log10() +
  scale_color_manual(breaks = c("D+", "D-", "mild"),
                          values = c("orangered", "blue", "green3")) +
  facet_wrap(~factor(Timepoint, levels = c('M3', 'M5+')), 
             scales = "free",
             ncol = 2) +
  theme_bw() +
  theme(strip.background =element_rect(fill="aliceblue")) +
  ggtitle("IgG vs PNT measures at the same time point") +
  xlab("B.1.1.7") + ylab("IgG BAU/ml") +
  stat_cor(method = "spearman", size = 3) +
  geom_smooth(method = "lm", se = F)
ggsave(paste0("MSimages/IgG vs B.1.1.7.png"), width = 20, height = 10, units = "cm")


Sero_PNT %>% 
  filter(!Timepoint == "PI")  %>% 
  filter(!(Timepoint == "W2" | Timepoint == "W4"))%>% 
  ggplot(aes(x = B.1.1.7, y = IgG, colour = factor(Dexa))) +
  geom_point(alpha = 0.7) +
  scale_y_log10() +
  labs(col = "Dexa") +
  scale_color_manual(breaks = c("D+", "D-", "mild"),
                      values = c("orangered", "blue", "green3")) +
  facet_wrap(~factor(Timepoint, levels = c('M3', 'M5+')), 
             scales = "free",
             ncol = 2) +
  theme_bw() +
  theme(strip.background =element_rect(fill="aliceblue")) +
  ggtitle("IgG vs PNT measures at the same time point") +
  xlab("B.1.1.7") + ylab("IgG BAU/ml") +
  stat_cor(method = "spearman", size = 3) +
  geom_smooth(method = "lm", se = F)
ggsave(paste0("MSimages/IgG vs B.1.1.7 slopeByDexa.png"), width = 20, height = 10, units = "cm")


# IgG vs B.1.617.2

Sero_PNT %>% 
  filter(!Timepoint == "PI")  %>% 
  filter(!(Timepoint == "W2" | Timepoint == "W4"))%>% 
  ggplot(aes(x = B.1.617.2, y = IgG)) +
  geom_point(alpha = 0.7, aes(colour = factor(Dexa))) +
  scale_y_log10() +
  labs(col = "Dexa") +
  scale_color_manual(breaks = c("D+", "D-", "mild"),
                          values = c("orangered", "blue", "green3")) +
  facet_wrap(~factor(Timepoint, levels = c('M3', 'M5+')), 
             scales = "free",
             ncol = 2) +
  theme_bw() +
  theme(strip.background =element_rect(fill="aliceblue")) +
  ggtitle("IgG vs PNT measures at the same time point") +
  xlab("B.1.617.2") + ylab("IgG BAU/ml") +
  stat_cor(method = "spearman", size = 3) +
  geom_smooth(method = "lm", se = F)
ggsave(paste0("MSimages/IgG vs B.1.617.2.png"), width = 20, height = 10, units = "cm")


Sero_PNT %>% 
  filter(!Timepoint == "PI")  %>% 
  filter(!(Timepoint == "W2" | Timepoint == "W4"))%>% 
  ggplot(aes(x = B.1.617.2, y = IgG, colour = factor(Dexa))) +
  geom_point(alpha = 0.7) +
  scale_y_log10() +
  labs(col = "Dexa") +
  scale_color_manual(breaks = c("D+", "D-", "mild"),
                          values = c("orangered", "blue", "green3")) +
  facet_wrap(~factor(Timepoint, levels = c('M3', 'M5+')), 
             scales = "free",
             ncol = 2) +
  theme_bw() +
  theme(strip.background =element_rect(fill="aliceblue")) +
  ggtitle("IgG vs PNT measures at the same time point") +
  xlab("B.1.617.2") + ylab("IgG BAU/ml") +
  stat_cor(method = "spearman", size = 3) +
  geom_smooth(method = "lm", se = F)
ggsave(paste0("MSimages/IgG vs B.1.617.2 slopeByDexa.png"), width = 20, height = 10, units = "cm")

```

```{r Associatin of IgG and SRT at timepoints}
Sero_SRT <- sero %>%
  select(PatID_Studie1, Dexa, Timepoint, IgG) %>% 
  full_join(facs, .)

for(i in SRT)
{
  print(
    Sero_SRT %>% 
      filter(Marker2 == "CD40L+ GrzB+" | Marker2 == "CD137+ GrzB+") %>% 
      filter(Marker1=="CD4") %>% 
      filter(!(Timepoint == "PI" | Timepoint == "VC")) %>% 
      ggplot(aes(x = IgG, y = !!sym(i))) +
      geom_point(alpha = 0.7, aes(color = factor(Dexa))) +
      scale_y_log10() +
      labs(col = "Dexa") +
      scale_color_manual(breaks = c("D+", "D-", "mild"),
                          values = c("orangered", "blue", "green3")) +
      facet_wrap(~Marker2, scales ="free") +
      # facet_wrap(~factor(Marker2, levels = c("CD40L+ GrzB+",
      #                                        "CD137+ GrzB+")),
      #            scales = "free") +
      theme_bw() +
      theme(strip.background =element_rect(fill="aliceblue")) +
      ggtitle("IgG vs SRT (CD4)") +
      xlab("IgG BAU/ml") +
      stat_cor(method = "spearman", size = 3.5) +
      geom_smooth(method = "lm", se = F))
  ggsave(paste0("MSimages/IgG vs ", i, " all markers.png"), width = 20, height = 10, units = "cm")
}
```

```{r Associatin of PNT and SRT at timepoints}
PNT_SRT <- PNT %>%
  select(PatID_Studie1, Dexa, Timepoint, B.1.1.7, B.1.617.2, exclude_B.1.1.7, exclude_B.1.617.2) %>% 
  full_join(facs, .)

# B.1.1.7 vs S1
print(PNT_SRT %>%
    filter(Marker1 == "CD4") %>%
    filter(!(Timepoint == "PI" | Timepoint == "VC")) %>% 
    filter(Marker2 == "CD40L+ IFN-g+" | Marker2 == "CD40L+ IL-21+" | Marker2 == "CD137+ IL-21+") %>% 
    filter(exclude_B.1.1.7 == 0) %>% 
    as.data.frame() %>%
    ggplot(., aes(x = B.1.1.7, y = S1)) +
      geom_point(alpha = 0.7, aes(color = factor(Dexa))) +
      scale_y_log10() +
      labs(col = "Dexa") +
      scale_color_manual(breaks = c("D+", "D-", "mild"),
                          values = c("orangered", "blue", "green3")) +
      theme_bw() + 
      facet_wrap(~Marker2, scales = "free") +
      # facet_wrap(~factor(Marker2, levels = c("CD40L+ IFN-g+",
      #                                        "CD40L+ IL-21+",
      #                                        "CD137+ IL-21+")),
      #            scales = "free") +
      theme(strip.background =element_rect(fill="aliceblue")) +
      ggtitle(paste("B.1.1.7 vs S1")) +
      stat_cor(method = "spearman", size = 4))
ggsave("MSimages/B.1.1.7 vs S1 all markers.png", width = 20, height = 10, units = "cm")

# B.1.1.7 vs S2
print(PNT_SRT %>%
    filter(Marker1 == "CD4") %>%
    filter(!(Timepoint == "PI" | Timepoint == "VC")) %>% 
    filter(Marker2 == "CD137+ IFN-g+" | Marker2 == "CD40L+ IL-21+" | Marker2 == "CD137+ TNF-a") %>% 
    filter(exclude_B.1.1.7 == 0) %>% 
    as.data.frame() %>%
    ggplot(., aes(x = B.1.1.7, y = S2)) +
      geom_point(alpha = 0.7, aes(color = factor(Dexa))) +
      scale_y_log10() +
      labs(col = "Dexa") +
      scale_color_manual(breaks = c("D+", "D-", "mild"),
                          values = c("orangered", "blue", "green3")) +
      theme_bw() + 
      facet_wrap(~Marker2, scales = "free") +
      # facet_wrap(~factor(Marker2, levels = c("CD137+ IFN-g+",
      #                                        "CD40L+ IL-21+",
      #                                        "CD137+ TNF-a")),
      #            scales = "free") +
      theme(strip.background =element_rect(fill="aliceblue")) +
      ggtitle(paste("B.1.1.7 vs S2")) +
      stat_cor(method = "spearman", size = 4))
ggsave("MSimages/B.1.1.7 vs S2 all markers.png", width = 20, height = 10, units = "cm")

# B.1.617.2 vs S1
print(PNT_SRT %>%
    filter(Marker1 == "CD4") %>%
    filter(!(Timepoint == "PI" | Timepoint == "VC")) %>% 
    filter(Marker2 == "CD40L+ IL-21+") %>% 
    filter(exclude_B.1.617.2 == 0) %>% 
    as.data.frame() %>%
    ggplot(., aes(x = B.1.617.2, y = S1)) +
      geom_point(alpha = 0.7, aes(color = factor(Dexa))) +
      
      scale_y_log10() +
      labs(col = "Dexa") +
      scale_color_manual(breaks = c("D+", "D-", "mild"),
                          values = c("orangered", "blue", "green3")) +
      theme_bw() + 
      facet_wrap(~Marker2, scales = "free") +
      # facet_wrap(~factor(Marker2),#, levels = c("CD40L+ CD137+",
      #                                        #"CD40L+ IL-21+",
      #                                        #"CD40L+ TNF-a+")),
      #            scales = "free") +
      theme(strip.background =element_rect(fill="aliceblue")) +
      ggtitle(paste("B.1.617.2 vs S1")) +
      stat_cor(method = "spearman", size = 4))
ggsave(paste0("MSimages/B.1.617.2 vs S1 all markers.png"), width = 10, height = 10, units = "cm")

# B.1.617.2 vs S2
print(PNT_SRT %>%
    filter(Marker1 == "CD4") %>%
    filter(!(Timepoint == "PI" | Timepoint == "VC")) %>% 
    filter(Marker2 == "CD40L+ IL-21+") %>% 
    filter(exclude_B.1.617.2 == 0) %>% 
    as.data.frame() %>%
    ggplot(., aes(x = B.1.617.2, y = S2)) +
      geom_point(alpha = 0.7, aes(color = factor(Dexa))) +
      
      scale_y_log10() +
      labs(col = "Dexa") +
      scale_color_manual(breaks = c("D+", "D-", "mild"),
                          values = c("orangered", "blue", "green3")) +
      theme_bw() + 
      facet_wrap(~Marker2, scales = "free") +
      # facet_wrap(~factor(Marker2),#, levels = c("CD40L+ CD137+",
      #                                        #"CD40L+ IL-21+",
      #                                        #"CD40L+ TNF-a+")),
      #            scales = "free") +
      theme(strip.background =element_rect(fill="aliceblue")) +
      ggtitle(paste("B.1.617.2 vs S2")) +
      stat_cor(method = "spearman", size = 4))
ggsave(paste0("MSimages/B.1.617.2 vs S2 all markers.png"), width = 10, height = 10, units = "cm")

```

```{r early SRT vs late IgG}

# SRT W2 vs IgG after month 5
SRT_W2_sero_M5_pat <- sero %>% 
  left_join(., facs, by = "PatID_Studie1") %>% 
  group_by(PatID_Studie1) %>% 
  rename(Sero_time = Timepoint.x, SRT_time = Timepoint.y) %>% 
  filter(Sero_time == "M5+", SRT_time == "W2")

for(i in SRT)
{  print(
    SRT_W2_sero_M5_pat %>% 
      filter(Marker1 == "CD4") %>% 
      ggplot(aes(x = IgG, y = !!sym(i))) + 
      geom_point(alpha = 0.7, aes(colour = factor(Dexa.x))) + 
      labs(col = "Dexa") +
      scale_color_manual(breaks = c("D+", "D-", "mild"),
                        values=c("orangered", "blue", "green3")) +
      facet_wrap(~factor(Marker2, levels = c("CD40L+ CD137+","CD40L+ GrzB+",
                                             "CD40L+ IFN-g+","CD40L+ IL-21+",
                                             "CD40L+ TNF-a+","CD137+ GrzB+",
                                             "CD137+ IFN-g+","CD137+ IL-21+",
                                             "CD137+ TNF-a+","CD137+ GrzB-")),
                 scales = "free_y", ncol = 2) +
      stat_cor(method = "spearman", size = 4) +
      #stat_smooth(method = "lm", se = "F") +
      theme_bw() +
      theme(strip.background =element_rect(fill="aliceblue")) +
      xlab("IgG @ M5+") +
      ylab(paste0(i, " @ W2")) +
      ggtitle("CD4 early SRT vs later IgG")
  )
ggsave(paste("MSimages/IgG@M5+ vs CD4 ", i, "@W2.png"), width = 20, height = 20, units = "cm")
}
  
for(i in SRT)
{  print(
    SRT_W2_sero_M5_pat %>% 
      filter(Marker1 == "CD8") %>% 
      ggplot(aes(x = IgG, y = !!sym(i))) + 
      geom_point(alpha = 0.7, aes(colour = factor(Dexa.x))) + 
      labs(col = "Dexa") +
      scale_color_manual(breaks = c("D+", "D-", "mild"),
                        values=c("orangered", "blue", "green3")) +
      facet_wrap(~factor(Marker2, levels = c("CD40L+ CD137+","CD40L+ GrzB+",
                                             "CD40L+ IFN-g+","CD40L+ IL-21+",
                                             "CD40L+ TNF-a+","CD137+ GrzB+",
                                             "CD137+ IFN-g+","CD137+ IL-21+",
                                             "CD137+ TNF-a+","CD137+ GrzB-")),
                 scales = "free_y", ncol = 2) +
      stat_cor(method = "spearman", size = 4) +
      #stat_smooth(method = "lm", se = "F") +
      theme_bw() +
      theme(strip.background =element_rect(fill="aliceblue")) +
      xlab("IgG @ M5+") +
      ylab(paste0(i, " @ W2")) +
      ggtitle("CD8 early SRT vs later IgG")
  )
ggsave(paste("MSimages/IgG@M5+ vs CD8 ", i, "@W2.png"), width = 20, height = 20, units = "cm")
}
```

```{r early SRT vs late PNT}

PNT_SRT_diff_timepoints <- PNT %>% 
  left_join(., facs, by = "PatID_Studie1") %>% 
  group_by(PatID_Studie1) %>% 
  rename(SRT_time = Timepoint.y) %>% 
  rename(PNT_time = Timepoint.x)

for(i in SRT)
 { print(
    PNT_SRT_diff_timepoints %>% 
      filter(PNT_time == "M5+", SRT_time == "W2") %>% 
      filter(Marker1 == "CD4") %>% 
      filter(exclude_B.1.1.7 == 0) %>% 
      ggplot(aes(x = B.1.1.7, y = !!sym(i))) + 
      geom_point(alpha = 0.7, aes(colour = factor(Dexa.x))) + 
      labs(col = "Dexa") +
      scale_color_manual(breaks = c("D+", "D-", "mild"),
                        values=c("orangered", "blue", "green3")) +
      facet_wrap(~factor(Marker2, levels = c("CD40L+ CD137+","CD40L+ GrzB+",
                                             "CD40L+ IFN-g+","CD40L+ IL-21+",
                                             "CD40L+ TNF-a+","CD137+ GrzB+",
                                             "CD137+ IFN-g+","CD137+ IL-21+",
                                             "CD137+ TNF-a+","CD137+ GrzB-")),
                 scales = "free_y", ncol = 2) +
      stat_cor(method = "spearman", size = 4) +
      #stat_smooth(method = "lm", se = "F") +
      theme_bw() +
      theme(strip.background =element_rect(fill="aliceblue")) +
      xlab("PNT (B.1.1.7) @ M5+") +
      ylab(paste0(i, " @ W2")) +
      ggtitle("CD4 early SRT vs later PNT")
  )
ggsave(paste("MSimages/B.1.1.7@M5+ vs CD4 ", i, "@W2.png"), width = 20, height = 20, units = "cm")
}

for(i in SRT)
 { print(
    PNT_SRT_diff_timepoints %>% 
      filter(PNT_time == "M5+", SRT_time == "W2") %>% 
      filter(Marker1 == "CD8") %>% 
      filter(exclude_B.1.1.7 == 0) %>% 
      ggplot(aes(x = B.1.1.7, y = !!sym(i))) + 
      geom_point(alpha = 0.7, aes(colour = factor(Dexa.x))) + 
      labs(col = "Dexa") +
      scale_color_manual(breaks = c("D+", "D-", "mild"),
                        values=c("orangered", "blue", "green3")) +
      facet_wrap(~factor(Marker2, levels = c("CD40L+ CD137+","CD40L+ GrzB+",
                                             "CD40L+ IFN-g+","CD40L+ IL-21+",
                                             "CD40L+ TNF-a+","CD137+ GrzB+",
                                             "CD137+ IFN-g+","CD137+ IL-21+",
                                             "CD137+ TNF-a+","CD137+ GrzB-")),
                 scales = "free_y", ncol = 2) +
      stat_cor(method = "spearman", size = 4) +
      #stat_smooth(method = "lm", se = "F") +
      theme_bw() +
      theme(strip.background =element_rect(fill="aliceblue")) +
      xlab("PNT (B.1.1.7) @ M5+") +
      ylab(paste0(i, " @ W2")) +
      ggtitle("CD8 early SRT vs later PNT")
  )
ggsave(paste("MSimages/B.1.1.7@M5+ vs CD8 ", i, "@W2.png"), width = 20, height = 20, units = "cm")
}

# B.1.617.2
for(i in SRT)
 { print(
    PNT_SRT_diff_timepoints %>% 
      filter(PNT_time == "M5+", SRT_time == "W2") %>% 
      filter(Marker1 == "CD4") %>% 
      filter(exclude_B.1.617.2 == 0) %>% 
      ggplot(aes(x = B.1.617.2, y = !!sym(i))) + 
      geom_point(alpha = 0.7, aes(colour = factor(Dexa.x))) + 
      labs(col = "Dexa") +
      scale_color_manual(breaks = c("D+", "D-", "mild"),
                        values=c("orangered", "blue", "green3")) +
      facet_wrap(~factor(Marker2, levels = c("CD40L+ CD137+","CD40L+ GrzB+",
                                             "CD40L+ IFN-g+","CD40L+ IL-21+",
                                             "CD40L+ TNF-a+","CD137+ GrzB+",
                                             "CD137+ IFN-g+","CD137+ IL-21+",
                                             "CD137+ TNF-a+","CD137+ GrzB-")),
                 scales = "free_y", ncol = 2) +
      stat_cor(method = "spearman", size = 4) +
      #stat_smooth(method = "lm", se = "F") +
      theme_bw() +
      theme(strip.background =element_rect(fill="aliceblue")) +
      xlab("PNT (B.1.617.2) @ M5+") +
      ylab(paste0(i, " @ W2")) +
      ggtitle("CD4 early SRT vs later PNT")
  )
ggsave(paste("MSimages/B.1.617.2@M5+ vs CD4 ", i, "@W2.png"), width = 20, height = 20, units = "cm")
}

for(i in SRT)
 { print(
    PNT_SRT_diff_timepoints %>% 
      filter(PNT_time == "M5+", SRT_time == "W2") %>% 
      filter(Marker1 == "CD8") %>% 
      filter(exclude_B.1.617.2 == 0) %>% 
      ggplot(aes(x = B.1.617.2, y = !!sym(i))) + 
      geom_point(alpha = 0.7, aes(colour = factor(Dexa.x))) + 
      labs(col = "Dexa") +
      scale_color_manual(breaks = c("D+", "D-", "mild"),
                        values=c("orangered", "blue", "green3")) +
      facet_wrap(~factor(Marker2, levels = c("CD40L+ CD137+","CD40L+ GrzB+",
                                             "CD40L+ IFN-g+","CD40L+ IL-21+",
                                             "CD40L+ TNF-a+","CD137+ GrzB+",
                                             "CD137+ IFN-g+","CD137+ IL-21+",
                                             "CD137+ TNF-a+","CD137+ GrzB-")),
                 scales = "free_y", ncol = 2) +
      stat_cor(method = "spearman", size = 4) +
      #stat_smooth(method = "lm", se = "F") +
      theme_bw() +
      theme(strip.background =element_rect(fill="aliceblue")) +
      xlab("PNT (B.1.617.2) @ M5+") +
      ylab(paste0(i, " @ W2")) +
      ggtitle("CD8 early SRT vs later PNT")
  )
ggsave(paste("MSimages/B.1.617.2@M5+ vs CD8 ", i, "@W2.png"), width = 20, height = 20, units = "cm")
}

```

```{r Evolution of T-cells, PNT and IgG before and after dexa}

# serology

sero_valid_dates <- sero %>% 
  filter(!is.na(`#Ende Dexa`))

# make it wide
print(
  sero_evol <- sero_valid_dates %>% 
  # select(Studie1,
  #        PatID_Studie1,
  #        Dexa,
  #        Timepoint,
  #        Marker2,
  #        S1) %>%
  #group_by(PatID_Studie1) %>%
  mutate(row = row_number()) %>%
  mutate(Entnahmedatum = gsub(".", "-", Entnahmedatum, fixed = T)) %>% 
  mutate(`#Ende Dexa` = gsub(".", "-", `#Ende Dexa`, fixed = T)) %>%
  mutate(`#Start Dexa` = gsub(".", "-", `#Start Dexa`, fixed = T)) %>%
  mutate(End_to_sample = as.numeric(as.Date(Entnahmedatum, format = "%d-%m-%Y") - as.Date(`#Ende Dexa`, format = "%d-%m-%Y"))) %>% 
  mutate(Dexa_end_zero = rep(0,nrow(.))) %>% 
  # tidyr::pivot_wider(id_cols = c(PatID_Studie1, Studie1, Dexa, 
  #                                `#Start Dexa`, `#Ende Dexa`, 
  #                                `#Days Start Dexa PSO`, `#Duration Dexa`),
  #                    names_from = Timepoint,
  #                    values_from = IgG,
  #                    values_fn = list) %>%
  ggplot(aes(x = End_to_sample, 
             y = IgG, 
             colour = factor(Dexa),
             group = factor(PatID_Studie1))) +
        labs(col = "Dexa") +
        #theme(axis.text.x = element_text(angle = 90)) +
        #geom_jitter(width = 0.1, alpha = 0.2) +
        geom_point(position = position_dodge(0.4), alpha = 0.5) +
        scale_y_log10() +
        #geom_boxplot(aes(fill = factor(Dexa)), width = 0.5, 
        #             colour = "gray47", alpha = 0.5, outlier.shape = NA) +
        scale_color_manual(breaks = c("1", "0", "3"),
                          values=c("orangered", "blue", "green3"),
                        labels = c("D+", "D-", "mild")) +
        scale_fill_manual(breaks = c("1", "0", "3"),
                          values=c("orangered", "blue", "green3"),
                        labels = c("D+", "D-", "mild")) +
        # facet_wrap(~factor(Marker2, levels = c("CD40L+ CD137+","CD40L+ GrzB+",
        #                                        "CD40L+ IFN-g+","CD40L+ IL-21+",
        #                                        "CD40L+ TNF-a+","CD137+ GrzB+",
        #                                        "CD137+ IFN-g+","CD137+ IL-21+",
        #                                        "CD137+ TNF-a+","CD137+ GrzB-")),
        #            scales = "free") +
        facet_wrap(. ~ factor(Dexa, levels = c('1', '0', '3')),
                 ncol = 3,
                 scales = "free") +
                 #labeller = labeller(Dexa = as_labeller(dexa.labels))) +
        geom_line(position = position_dodge(0.4), 
                  aes(group = factor(PatID_Studie1)), alpha = 0.8, 
                  size = 0.2) +
        xlab("Time point") +
        ggtitle("IgG evolution") +
        theme_bw() +
        #theme(legend.position = "none") +
        theme(strip.background =element_rect(fill="aliceblue")))

```