---
title: "SARS-CoV-2 reactive T-cells in COVID-19 - Figure 5"
output:
  html_document:
    toc: yes
    theme: united
    code_folding: hide
  pdf_document:
    toc: yes
---

```{r, echo = F}
knitr::opts_chunk$set(warning = F, message = F)
knitr::opts_chunk$set(fig.pos = "!H", out.extra = "", fig.width = 9, fig.height = 6)
#options(digits = 3)
#knitr::opts_chunk$set(dpi=150,fig.width=7)
```

```{r load_libraries, echo = F, message = F, warning = F}
library(sjPlot)
library(sjmisc)
library(readxl)
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(reshape2)
library(broom)
library(stringr)
library(MASS) # for rlm
library(ggthemes)
library(lmerTest)
library(glmm)
library(ggstatsplot)
#library(patchwork)
#library(kableExtra)
#library(rmarkdown)
```

## Load data tables
```{r load_datasets}
# delta alpha clinical table
PNT <- read_excel("../2022_05_19_PNT_CT.xlsx") %>% 
  dplyr::select(contains("Studie 1"),
         contains("PatID"),
         contains("exclude"),
         contains("Tag PSO"),
         contains("PSO/PI"),
         contains("Zeitraum"),
         contains("Serum"),
         contains("Dexa")) %>%
  rename(PatID_Studie1 = `PatID`,
         Studie1 = `Studie 1`,
         exclude_immuno = `# exclude (immunosuppression, other)`,
         exclude_B.1.1.7 = `#exclude for B1.1.7`,
         exclude_B.1.617.2 = `#exclude for B.1.617.2`,
         TagPSO = `Tag PSO`,
         Timepoint = `Zeitraum`,
         B.1.1.7 = `Serum ID50: Variant B.1.1.7`, 
         B.1.617.2 = `Serum ID50: Variant B.1.617.2`,
         BA.2 = `Serum ID50: Variant BA.2`,
         Dexa = `Dexamethason`) %>%
  mutate(PatID_Studie1 = str_replace(PatID_Studie1, c("C19-CB-"), "")) %>% 
  mutate(PatID_Studie1 = as.character(as.numeric(PatID_Studie1))) %>% 
  mutate(TagPSO = as.numeric(TagPSO)) %>%
  mutate(Studie1 = str_replace(Studie1, c("Pa-COVID-19"), "Pa-COVID")) %>% 
  mutate(PatID_Studie1 = paste(tolower(paste(substr(Studie1, 1, 2))), 
                               tolower(paste(substr(Studie1, (nchar(Studie1)-1), nchar(Studie1)), 
                                             PatID_Studie1, 
                                             sep = "")),
                               sep = "")) %>%
  mutate(exclude_immuno = as.numeric(replace_na(exclude_immuno, 0))) %>% 
  filter(exclude_immuno == 0) %>% 
  mutate(exclude_B.1.1.7 = as.numeric(replace_na(exclude_B.1.1.7, 0))) %>% 
  #mutate(Timepoint = str_replace_all(Timepoint, c("5" = "6", "W4" = "M1"))) %>%
  mutate(exclude_B.1.617.2 = as.numeric(replace_na(exclude_B.1.617.2, 0))) %>% 
  mutate(Dexa = str_replace_all(Dexa, c("1" = "D+", "0" = "D-", "3" = "mild", "4" = "vaccine control")))

# FACS results
facs <- read_excel("../cleaned_FACS_mastertable 2022_04.xlsx") %>% 
  rename(ID = `Studie und PatID`,
         Timepoint = `Zeitraum`) %>% 
  separate(ID, c("Studie1", "PatID_Studie1"), sep = " ") %>% 
  filter(!is.na(CEFX) | !is.na(S1) | !is.na(S2) | !is.na(SEB)) %>%
  mutate(PatID_Studie1 = as.character(PatID_Studie1)) %>% 
  #filter(!(ausschliessen == 1)) %>% 
  mutate(Studie1 = str_replace(Studie1, c("Pa-COVID-19"), "Pa-COVID")) %>% 
  mutate(PatID_Studie1 = paste(tolower(paste(substr(Studie1, 1, 2))), 
                               tolower(paste(substr(Studie1, (nchar(Studie1)-1), nchar(Studie1)), 
                                             PatID_Studie1, 
                                             sep = "")),
                               sep = "")) %>% 
  mutate(Timepoint = str_replace_all(Timepoint, c("W 2"="W2"))) %>% 
  mutate(Dexa = str_replace_all(Dexa, c("1" = "D+", "0" = "D-", "3" = "mild", "4" = "vaccine control")))


# meta data
meta <- read_excel("../metadata 2022 05 24 CT.xlsx") %>%
  dplyr::select(#contains("sanity"),
         contains("Studie 1"),
         contains("Alter / Geschaetztes Alter bei Einschluss gr 3 Jahre"),
         contains("Geschlecht bei der Geburt"),
         contains("Dexamethason"),
         contains("Immunosuppression"),
         contains("Bemerkung"),
         contains("Start Dexa"),
         contains("Ende Dexa")) %>% 
  rename(PatID_Studie1 = `PatID Studie 1`, 
         Age = `Alter / Geschaetztes Alter bei Einschluss gr 3 Jahre`, 
         Sex = `Geschlecht bei der Geburt` ,
         Studie1 = `Studie 1`,
         Dexa = Dexamethason) %>%
  mutate(PatID_Studie1 = as.character(PatID_Studie1)) %>% 
  mutate(Immunosuppression = as.numeric(replace_na(Immunosuppression, 0))) %>%
  filter(Immunosuppression == 0) %>% 
  mutate(PatID_Studie1 = str_replace(PatID_Studie1, c("C19-CB-"), "")) %>%
  mutate(PatID_Studie1 = as.character(as.numeric(PatID_Studie1))) %>% 
  mutate(Studie1 = str_replace(Studie1, c("Pa-COVID-19"), "Pa-COVID")) %>% 
  mutate(PatID_Studie1 = paste(tolower(paste(substr(Studie1, 1, 2))), 
                               tolower(paste(substr(Studie1, (nchar(Studie1)-1), nchar(Studie1)), 
                                             PatID_Studie1, 
                                             sep = "")),
                               sep = "")) %>% 
  mutate(Dexa = str_replace_all(Dexa, c("1" = "D+", "0" = "D-", "3" = "mild", "4" = "vaccine control")))

# serology
sero <- read_excel("../2022_05_18_Serol_CT.xlsx") %>% 
  dplyr::select(contains("Studie 1"),
         contains("Entnahmedatum"),
         contains("Tag PSO"),
         contains("Bemerkung"),
         contains("Zeitraum"),
         contains("IgG"),
         contains("Dexa"),
         contains("ausschliessen (Immunsuppression, other)"),
         "PatID") %>% 
  rename(PatID_Studie1 = `PatID`,
         Studie1 = `Studie 1`,
         IgG = `IgG Value <7 set to 1`,
         TagPSO = `Tag PSO`, 
         Timepoint = Zeitraum, 
         Dexa = `Dexamethason`,
         ausschliessen_imm = `ausschliessen (Immunsuppression, other)`) %>% 
  mutate(ausschliessen_imm = replace_na(ausschliessen_imm, 0)) %>%
  mutate(PatID_Studie1 = str_replace(PatID_Studie1, c("C19-CB-"), "")) %>% 
  mutate(PatID_Studie1 = as.character(as.numeric(PatID_Studie1))) %>% 
  mutate(IgG = as.numeric(str_replace(IgG, c(","), "\\."))) %>% 
  filter(!ausschliessen_imm == 1) %>% 
  mutate(Studie1 = str_replace(Studie1, c("Pa-COVID-19"), "Pa-COVID")) %>% 
  mutate(PatID_Studie1 = str_replace(PatID_Studie1, c("C19-CB-"), "")) %>%
  mutate(PatID_Studie1 = as.character(as.numeric(PatID_Studie1))) %>% 
  mutate(PatID_Studie1 = paste(tolower(paste(substr(Studie1, 1, 2))), 
                               tolower(paste(substr(Studie1, (nchar(Studie1)-1), nchar(Studie1)), 
                                             PatID_Studie1, 
                                             sep = "")),
                               sep = "")) %>% 
  mutate(Timepoint = str_replace_all(Timepoint, c("5" = "6"))) %>%
  mutate(Dexa = str_replace_all(Dexa, c("1" = "D+", "0" = "D-", "3" = "mild", "4" = "vaccine control")))

SRT <- c("S1", "S2")
strain <- c("B.1.1.7", "B.1.617.2")
level_order <- c('1', '0', '3')
```

```{r}

facs_use <- facs %>% 
  filter(Marker == "CD4 CD40L+ CD137+" | Marker == "CD4 CD40L+ TNF-a+") %>% 
  dplyr::select(-c(CEFX, SEB, S2)) %>% 
  na.omit %>% 
  #rename(SRT_Timepoint = Timepoint) %>% 
  spread(Marker, S1)

PNT_use_B.1.1.7 <- PNT %>% 
  dplyr::select(-c(exclude_immuno, `PSO/PI`, exclude_B.1.617.2, B.1.617.2, BA.2, `PatID Studie 2`)) %>% 
  filter(exclude_B.1.1.7 == 0) %>% 
  dplyr::select(-c(exclude_B.1.1.7))
#%>% 
  # rename(B.1.1.7_Timepoint = Timepoint,
  #        B.1.1.7_TagPSO = TagPSO)

PNT_use_B.1.617.2 <- PNT %>% 
  dplyr::select(-c(exclude_immuno, `PSO/PI`, exclude_B.1.1.7, B.1.1.7, BA.2, `PatID Studie 2`)) %>% 
  filter(exclude_B.1.617.2 == 0) %>% 
  dplyr::select(-c(exclude_B.1.617.2)) #%>% 
  # rename(B.1.617.2_Timepoint = Timepoint,
  #        B.1.617.2_TagPSO = TagPSO)

PNT_use_BA.2 <- PNT %>% 
  dplyr::select(-c(exclude_immuno, `PSO/PI`, exclude_B.1.1.7, B.1.1.7, exclude_B.1.617.2, B.1.617.2, `PatID Studie 2`)) %>% 
  drop_na(BA.2) #%>% 
  # rename(BA.2_Timepoint = Timepoint,
  #        BA.2_TagPSO = TagPSO)

IgG_use <- sero %>% 
  dplyr::select(-c(Entnahmedatum, starts_with("Bemerkung"), `IgG Value BAU/ml >=7.1 reactive`,
                   `Tag post Dexa start`, starts_with("#"), Dexamethasone, ausschliessen_imm)) #%>% 
  # rename(IgG_Timepoint = Timepoint,
  #        IgG_TagPSO = TagPSO)
# 
# merged_dfs <- list(facs_use, PNT_use_B.1.1.7, PNT_use_B.1.617.2, PNT_use_BA.2, IgG_use) %>% 
#   reduce(full_join, by = c("PatID_Studie1", "Studie1", "Dexa"))


```

```{r}
IgG_use_wide <- IgG_use %>% 
  pivot_wider(names_from = Timepoint, values_from = c(IgG, TagPSO), names_glue = "IgG_{.value}_{Timepoint}")

facs_use_137_wide <- facs_use %>% 
  dplyr::select(-`CD4 CD40L+ TNF-a+`) %>% 
  pivot_wider(names_from = Timepoint, values_from = `CD4 CD40L+ CD137+`, names_glue = "{.value}_{Timepoint}")

facs_use_TNF_wide <- facs_use %>% 
  dplyr::select(-`CD4 CD40L+ CD137+`) %>% 
  pivot_wider(names_from = Timepoint, values_from = `CD4 CD40L+ TNF-a+`, names_glue = "{.value}_{Timepoint}")

PNT_use_B.1.1.7_wide <- PNT_use_B.1.1.7 %>% 
  pivot_wider(names_from = Timepoint, values_from = c(B.1.1.7, TagPSO), names_glue = "B.1.1.7_{.value}_{Timepoint}")

PNT_use_B.1.617.2_wide <- PNT_use_B.1.617.2 %>% 
  pivot_wider(names_from = Timepoint, values_from = c(B.1.617.2, TagPSO), names_glue = "B.1.617.2_{.value}_{Timepoint}")

PNT_use_BA.2_wide <- PNT_use_BA.2 %>% 
  pivot_wider(names_from = Timepoint, values_from = c(BA.2, TagPSO), names_glue = "BA.2_{.value}_{Timepoint}")
```

```{r}
patients <- meta %>% 
  mutate(Immunosuppression = replace_na(Immunosuppression, 0)) %>% 
  filter(Immunosuppression != 1) %>% 
  dplyr::select(-c(starts_with("#"), Bemerkung, Immunosuppression, Age, Sex)) # 215 patients


#timepoint <- data.frame(Timepoint = c("W2", "M1", "M3", "M6", "PI"))

# pat_tp <- data.frame(PatID_Studie1 = lapply(patients, function(x) rep(x, 5)),
#                      Timepoint = rep(timepoint, length(patients)))

facs137 <- full_join(patients, facs_use_137_wide)
facsTNF <- left_join(facs137, facs_use_TNF_wide)

PNT_B.1.1.7 <- left_join(facsTNF, PNT_use_B.1.1.7_wide)

PNT_B.1.617.2 <- left_join(PNT_B.1.1.7, PNT_use_B.1.617.2_wide)

PNT_BA.2 <- left_join(PNT_B.1.617.2, PNT_use_BA.2_wide)

IgG <- left_join(PNT_BA.2, IgG_use_wide)

set.seed(1)
randomID <- data.frame(PatID_Studie1 = IgG$PatID_Studie1) %>% 
  mutate(RandID = sample(10000, size = nrow(.), replace = F))
write.table(randomID, "Randomly_generated_patient_ID.csv", sep = ";", row.names = F, quote = F, dec = ".")

patdata <- IgG %>% 
  rename(Study = Studie1, Group = Dexa) %>% 
  left_join(., randomID) %>% 
  relocate(RandID, .after = Study) %>%
  dplyr::select(-c("PatID_Studie1")) %>%
  rename(PatientID = RandID) %>% 
  dplyr::select(Study, PatientID, Group, 
                `CD4 CD40L+ CD137+_W2`, `CD4 CD40L+ CD137+_M1`, `CD4 CD40L+ CD137+_M3`, `CD4 CD40L+ CD137+_M6`, `CD4 CD40L+ CD137+_PI`,
                `CD4 CD40L+ TNF-a+_W2`, `CD4 CD40L+ TNF-a+_M1`, `CD4 CD40L+ TNF-a+_M3`, `CD4 CD40L+ TNF-a+_M6`, `CD4 CD40L+ TNF-a+_PI`,
                `IgG_IgG_W2`, `IgG_IgG_M1`, `IgG_IgG_M3`, `IgG_IgG_M6`, `IgG_IgG_PI`,
                `IgG_TagPSO_W2`, `IgG_TagPSO_M1`, `IgG_TagPSO_M3`, `IgG_TagPSO_M6`, `IgG_TagPSO_PI`,
                `B.1.1.7_B.1.1.7_W2`, `B.1.1.7_B.1.1.7_M1`, `B.1.1.7_B.1.1.7_M3`, `B.1.1.7_B.1.1.7_M6`, `B.1.1.7_B.1.1.7_PI`,
                `B.1.1.7_TagPSO_W2`, `B.1.1.7_TagPSO_M1`, `B.1.1.7_TagPSO_M3`, `B.1.1.7_TagPSO_M6`, `B.1.1.7_TagPSO_PI`,
                `B.1.617.2_B.1.617.2_W2`, `B.1.617.2_B.1.617.2_M1`, `B.1.617.2_B.1.617.2_M3`, `B.1.617.2_B.1.617.2_M6`, `B.1.617.2_B.1.617.2_PI`,
                `B.1.617.2_TagPSO_W2`, `B.1.617.2_TagPSO_M1`, `B.1.617.2_TagPSO_M3`, `B.1.617.2_TagPSO_M6`, `B.1.617.2_TagPSO_PI`,
                `BA.2_BA.2_PI`, `BA.2_TagPSO_PI`) %>% 
  mutate(across(where(is.numeric), ~ round(., 3)))




write.table(patdata, "Patient_dataset_SRT_IgG_PNT_singlerow.csv", sep = ";", row.names = F, quote = F, dec = ".")

```


```{r}
rand <- read.csv("Randomly_generated_patientID.csv") %>% 
  mutate(Study = IgG$Studie1) %>% 
  mutate(PatientID = substr(IgG$PatID_Studie1, 5,7)) %>% 
  rename(shortenedID = PatID_Studie1) %>% 
  relocate(shortenedID, .after = PatientID) %>% 
  relocate(RandID, .after = shortenedID)

write.table(rand, "Randomly_generated_patientID.csv", sep = ";", row.names = F, quote = F, dec = ".")
```

```{r}
rand <- read.csv("Randomly_generated_patientID.csv")
dat <- read_excel("Patient_dataset_SRT_IgG_PNT.xlsx")

rand_ID <- rand %>% 
  mutate(study_ID = 
         case_when(Study == "COVIMMUNIZE" ~ paste0("COVIZE", RandomID),
                   Study == "COVIMMUN" ~ paste0("COVIM", RandomID),
                   Study == "Pa-COVID" ~ paste0("PA-COV", RandomID),
                   Study == "EICOV" ~ paste0("EIC", RandomID),
                   TRUE ~ Study))

write.table(rand_ID, "Randomly_generated_patientID.csv", sep = ";", row.names = F, quote = F, dec = ".")
```